export type CompanyDef = {
  slug: string;
  name: string;
  canonicalName?: string;
  ticker?: string;
  industry: string;
  description: string;
};

export const INDUSTRIES = [
  { slug: "beverages", name: "Beverages" },
  { slug: "consumer-goods", name: "Consumer Goods" },
  { slug: "insurance", name: "Insurance" },
  { slug: "finance", name: "Financial Services" },
  { slug: "railroads", name: "Railroads" },
  { slug: "energy", name: "Energy & Utilities" },
  { slug: "technology", name: "Technology" },
  { slug: "confectionery", name: "Confectionery" },
  { slug: "asset-management", name: "Asset Management" },
  { slug: "automotive", name: "Automotive" },
  { slug: "healthcare", name: "Healthcare" },
  { slug: "restaurants", name: "Restaurants" },
  { slug: "retail", name: "Retail" },
  { slug: "media", name: "Media" },
  { slug: "industrials", name: "Industrials" },
  { slug: "telecom", name: "Telecommunications" },
  { slug: "pharmaceuticals", name: "Pharmaceuticals & Biotech" },
  { slug: "e-commerce", name: "E-Commerce & Marketplaces" },
  { slug: "education", name: "Education & Edtech" },
  { slug: "hospitality", name: "Hospitality" },
  { slug: "steel-and-metals", name: "Steel, Metals & Mining" },
  { slug: "logistics", name: "Logistics & Ports" },
  { slug: "agribusiness", name: "Agribusiness & Dairy" },
];

export const COMPANIES: CompanyDef[] = [
  { slug: "coca-cola", name: "Coca-Cola", canonicalName: "The Coca-Cola Company", ticker: "KO", industry: "beverages", description: "Global beverage company; long-held Berkshire position and a recurring example of brand strength and pricing power." },
  { slug: "sees-candies", name: "See's Candies", canonicalName: "See's Candies, Inc.", industry: "confectionery", description: "West Coast confectioner whose acquisition taught Berkshire about brand power, pricing, and the nature of an economic moat." },
  { slug: "geico", name: "GEICO", canonicalName: "Government Employees Insurance Company", industry: "insurance", description: "Auto insurer Berkshire acquired in full; a recurring illustration of low-cost operator advantage and float." },
  { slug: "berkshire-hathaway", name: "Berkshire Hathaway", canonicalName: "Berkshire Hathaway Inc.", ticker: "BRK", industry: "finance", description: "Diversified holding company chaired by Warren Buffett; the reporting entity for the annual letters." },
  { slug: "american-express", name: "American Express", canonicalName: "American Express Company", ticker: "AXP", industry: "finance", description: "Payments network company; a long-held Berkshire investment discussed in the context of brand and network effects." },
  { slug: "wells-fargo", name: "Wells Fargo", canonicalName: "Wells Fargo & Company", ticker: "WFC", industry: "finance", description: "Banking company; historically a large Berkshire bank holding, later reduced." },
  { slug: "bnsf", name: "BNSF Railway", canonicalName: "BNSF Railway", industry: "railroads", description: "Class I freight railroad acquired by Berkshire; an example of durable infrastructure and capital intensity." },
  { slug: "berkshire-energy", name: "Berkshire Hathaway Energy", industry: "energy", description: "Regulated utility and energy business; illustrates long-horizon capital deployment." },
  { slug: "apple", name: "Apple", canonicalName: "Apple Inc.", ticker: "AAPL", industry: "technology", description: "Consumer technology company; Berkshire's largest reported equity holding in the 2010s–2020s." },
  { slug: "gillette", name: "Gillette", canonicalName: "The Gillette Company", industry: "consumer-goods", description: "Consumer products company later absorbed into Procter & Gamble; cited as a strong consumer brand." },
  { slug: "washington-post", name: "Washington Post", canonicalName: "The Washington Post Company", industry: "media", description: "Media company Berkshire held for decades; an early lesson in business economics before ownership." },
  { slug: "usair", name: "USAir", canonicalName: "US Airways Group, Inc.", industry: "industrials", description: "Airline preferred stake cited as a mistake where industry economics overwhelmed the security." },
  { slug: "salomon", name: "Salomon Brothers", canonicalName: "Salomon Inc.", industry: "finance", description: "Investment bank where Berkshire took a preferred stake amid the 1991 Treasury scandal." },
  { slug: "conocophillips", name: "ConocoPhillips", ticker: "COP", industry: "energy", description: "Energy company; Berkshire bought near the 2008 oil peak, later acknowledged as mistimed." },
  { slug: "ibm", name: "IBM", canonicalName: "International Business Machines", ticker: "IBM", industry: "technology", description: "Technology holding Berkshire entered in 2011 and exited by 2018; a documented learning experience." },
  { slug: "kraft-heinz", name: "Kraft Heinz", ticker: "KHC", industry: "consumer-goods", description: "Packaged-food combine formed in 2015 with Berkshire participation; discussed around goodwill write-downs." },
  { slug: "petrochina", name: "PetroChina", ticker: "PTR", industry: "energy", description: "Chinese oil major Buffett bought on intrinsic value in 2002-2007 and sold when price caught value." },
  { slug: "byd", name: "BYD", ticker: "BYDDY", industry: "automotive", description: "Chinese EV and battery maker; Munger championed the position for Berkshire in Asia." },
  { slug: "moodys", name: "Moody's", canonicalName: "Moody's Corporation", ticker: "MCO", industry: "finance", description: "Ratings agency; long Berkshire holding illustrating toll-booth economics." },
  { slug: "goldman-sachs", name: "Goldman Sachs", ticker: "GS", industry: "finance", description: "Bank that sold Berkshire preferred stock during the 2008 crisis at crisis terms." },
  { slug: "general-electric", name: "General Electric", ticker: "GE", industry: "industrials", description: "Industrial conglomerate; received Berkshire crisis-era preferred investment in 2008." },
  { slug: "freddie-mac", name: "Freddie Mac", industry: "finance", description: "Mortgage agency Buffett owned early, exited before losses; a case study in regulatory risk." },
  { slug: "johnson-johnson", name: "Johnson & Johnson", ticker: "JNJ", industry: "healthcare", description: "Healthcare company held by Berkshire during the 2000s as a quality consumer-staple analog." },
  { slug: "procter-gamble", name: "Procter & Gamble", ticker: "PG", industry: "consumer-goods", description: "Consumer staples giant acquired via Gillette merger; later exchanged for other holdings." },
  { slug: "vanguard", name: "Vanguard", industry: "asset-management", description: "Bogle-founded mutual structure credited with igniting low-cost index investing." },
  { slug: "fidelity-magellan", name: "Fidelity Magellan Fund", industry: "asset-management", description: "Peter Lynch's fund, whose 1977-1990 record underpins his public teachings." },
  { slug: "dunkin", name: "Dunkin'", industry: "restaurants", description: "Donut chain Lynch used to illustrate finding great stocks in everyday life." },
  { slug: "pepsi", name: "PepsiCo", ticker: "PEP", industry: "beverages", description: "Beverage-snack company appearing in Lynch's stories about institutional neglect of consumer winners." },
  { slug: "volvo", name: "Volvo", industry: "automotive", description: "Swedish automaker Lynch famously owned after researching its cars rather than Wall Street reports." },
  { slug: "fannie-mae", name: "Fannie Mae", industry: "finance", description: "Mortgage finance company Lynch held successfully before government conservatorship changed its nature." },
  { slug: "northern-pipeline", name: "Northern Pipeline", industry: "energy", description: "Standard Oil spinoff Graham mined for liquidation value in his 1920s hidden-value work." },
  { slug: "graham-newman", name: "Graham-Newman Corporation", industry: "asset-management", description: "Graham's investment partnership where Buffett trained before starting his own partnership." },
  { slug: "oaktree", name: "Oaktree Capital", industry: "asset-management", description: "Alternative investment firm Howard Marks co-founded; publisher of his client memos." },
  { slug: "toyota", name: "Toyota", ticker: "TM", industry: "automotive", description: "Automaker cited in quality-and-efficiency discussions across investor writings." },
  { slug: "motorola", name: "Motorola", ticker: "MOT", industry: "technology", description: "Electronics and communications company; Philip Fisher's flagship long-term growth holding." },
  { slug: "texas-instruments", name: "Texas Instruments", ticker: "TXN", industry: "technology", description: "Semiconductor company Fisher backed in its early decades; a canonical growth-investing case." },
  { slug: "icahn-enterprises", name: "Icahn Enterprises", ticker: "IEP", industry: "finance", description: "Carl Icahn's public holding company and the vehicle for his activist campaigns." },
  { slug: "trans-world-airlines", name: "Trans World Airlines", canonicalName: "Trans World Airlines, Inc. (TWA)", industry: "industrials", description: "Airline Icahn took private in a leveraged buyout; a defining and costly episode of his early raid years." },
  { slug: "rjr-nabisco", name: "RJR Nabisco", industry: "consumer-goods", description: "Tobacco-food combine targeted by Icahn and later KKR; emblematic of 1980s corporate-control battles." },
  { slug: "texaco", name: "Texaco", industry: "energy", description: "Oil major Icahn pressed for restructuring after the Pennzoil judgment turmoil." },
  { slug: "ebay", name: "eBay", ticker: "EBAY", industry: "technology", description: "Marketplace company Icahn publicly pressed to spin off PayPal in 2014." },
  { slug: "moto-solutions", name: "Motorola Solutions", ticker: "MSI", industry: "technology", description: "Communications-equipment company that emerged from Icahn's push to break up Motorola." },
  { slug: "gen-re", name: "General Re", industry: "insurance", description: "Reinsurer Berkshire acquired in 1998; underwriting discipline lessons followed." },
  { slug: "netjets", name: "NetJets", industry: "industrials", description: "Fractional jet ownership business acquired by Berkshire in 1998." },
  { slug: "helzberg", name: "Helzberg Diamonds", industry: "retail", description: "Jewelry retailer sold to Berkshire by its owner with a handshake deal." },
  { slug: "nebraska-furniture-mart", name: "Nebraska Furniture Mart", industry: "retail", description: "Rose Blumkin's Omaha furniture store; Berkshire's favorite story of operating excellence." },
  { slug: "jordans-furniture", name: "Jordan's Furniture", industry: "retail", description: "Massachusetts furniture retailer acquired by Berkshire in 1999." },
  { slug: "flight-safety", name: "FlightSafety International", industry: "industrials", description: "Aviation training company acquired by Berkshire; recurring quality-business example." },
  { slug: "reliance-communications", name: "Reliance Communications", industry: "telecom", description: "Anil Ambani's telecom arm, later wound down." },
  { slug: "adani-enterprises", name: "Adani Enterprises", industry: "industrials", description: "Adani group's incubation and trading arm." },
  { slug: "adani-green-energy", name: "Adani Green Energy", industry: "energy", description: "Adani group's renewable-energy arm." },
  { slug: "adani-group", name: "Adani Group", industry: "industrials", description: "Ports-to-energy conglomerate built by Gautam Adani." },
  { slug: "adani-ports", name: "Adani Ports & SEZ", industry: "logistics", description: "Adani group's ports and logistics arm." },
  { slug: "adani-power", name: "Adani Power", industry: "energy", description: "Adani group's thermal power arm." },
  { slug: "adani-total-gas", name: "Adani Total Gas", industry: "energy", description: "Adani-Total joint venture in city gas distribution." },
  { slug: "air-india", name: "Air India", industry: "industrials", description: "Flag carrier founded by the Tatas in 1932, nationalised and later re-privatised." },
  { slug: "amul", name: "Amul", industry: "agribusiness", description: "Gujarat cooperative dairy brand; the White Revolution's consumer face." },
  { slug: "bajaj-auto", name: "Bajaj Auto", industry: "automotive", description: "Bajaj group two- and three-wheeler manufacturer." },
  { slug: "bajaj-finserv", name: "Bajaj Finserv", industry: "finance", description: "Bajaj group financial-services holding company." },
  { slug: "bajaj-group", name: "Bajaj Group", industry: "industrials", description: "Conglomerate descended from Jamnalal Bajaj." },
  { slug: "bharatpe", name: "BharatPe", industry: "finance", description: "Ashneer Grover-co-founded merchant payments and lending firm." },
  { slug: "bharti-airtel", name: "bharti-airtel", industry: "industrials" },
  { slug: "bharti-enterprises", name: "bharti-enterprises", industry: "industrials" },
  { slug: "big-bazaar", name: "Big Bazaar", industry: "retail", description: "Future Group's value-retail chain." },
  { slug: "biocon", name: "Biocon", industry: "pharmaceuticals", description: "Kiran Mazumdar-Shaw-founded biotechnology firm." },
  { slug: "birla-group", name: "Birla Group", industry: "industrials", description: "Conglomerate descended from G.D. Birla; diversified across cement, metals and viscose." },
  { slug: "bisleri", name: "Bisleri", industry: "consumer-goods", description: "Ramesh Chauhan's packaged-water brand." },
  { slug: "blinkit", name: "Blinkit", industry: "e-commerce", description: "Zomato's quick-commerce arm (formerly Grofers)." },
  { slug: "byjus", name: "BYJU'S", industry: "education", description: "Byju Raveendran's edtech firm; valuation collapse and insolvency 2022-24." },
  { slug: "dream11", name: "Dream11", industry: "e-commerce", description: "Harsh Jain-Bhavit Sheth fantasy-sports platform." },
  { slug: "flipkart", name: "Flipkart", industry: "e-commerce", description: "Bansals' e-commerce firm; sold to Walmart in 2018." },
  { slug: "freshworks", name: "Freshworks", industry: "technology", description: "Girish Mathrubootham-founded SaaS firm; Nasdaq-listed 2021." },
  { slug: "future-group", name: "Future Group", industry: "retail", description: "Kishore Biyani's retail house; insolvent 2020-22." },
  { slug: "gcmmf", name: "GCMMF", industry: "agribusiness", description: "Gujarat Cooperative Milk Marketing Federation; the Amul marketer." },
  { slug: "godrej-consumer", name: "Godrej Consumer Products", industry: "consumer-goods", description: "Godrej group FMCG arm." },
  { slug: "godrej-group", name: "Godrej Group", industry: "consumer-goods", description: "Conglomerate founded around the 1897 springless lock." },
  { slug: "hcl-technologies", name: "HCL Technologies", industry: "technology", description: "Shiv Nadar-founded IT-services firm." },
  { slug: "hero-cycles", name: "Hero Cycles", industry: "consumer-goods", description: "Munjal-family bicycle company; once the world's largest cycle maker." },
  { slug: "hero-motocorp", name: "Hero MotoCorp", industry: "automotive", description: "World's largest two-wheeler manufacturer by volume." },
  { slug: "hindustan-times", name: "Hindustan Times", industry: "media", description: "K.K. Birla branch daily newspaper." },
  { slug: "honasa-consumer", name: "Honasa Consumer", industry: "consumer-goods", description: "Mamaearth parent; listed 2023." },
  { slug: "honda-motorcycle-india", name: "Honda Motorcycle & Scooter India", industry: "automotive", description: "Hero Honda JV partner; the post-2011 independent operation." },
  { slug: "idea-cellular", name: "Idea Cellular", industry: "telecom", description: "Kumar Mangalam Birla group telecom arm, merged into Vodafone Idea." },
  { slug: "infosys", name: "Infosys", industry: "technology", description: "Narayana Murthy-co-founded IT-services firm; the offshore-services archetype." },
  { slug: "itc", name: "ITC Limited", industry: "consumer-goods", description: "Diversified cigarettes-FMCG-hotels-paperboard house chaired by Y.C. Deveshwar." },
  { slug: "jaguar-land-rover", name: "Jaguar Land Rover", industry: "automotive", description: "British luxury automaker acquired by Tata Motors in 2008." },
  { slug: "jindal-group", name: "Jindal Group", industry: "steel-and-metals", description: "O.P. Jindal-founded steel-and-power house, split among successors." },
  { slug: "jindal-steel-power", name: "Jindal Steel & Power", industry: "steel-and-metals", description: "Naveen Jindal-chaired steel-and-power operating company." },
  { slug: "mahindra-group", name: "Mahindra Group", industry: "industrials", description: "Tractors-to-IT conglomerate chaired by Anand Mahindra." },
  { slug: "mahindra-mahindra", name: "Mahindra & Mahindra", industry: "automotive", description: "Mahindra group's automotive and tractor flagship." },
  { slug: "mamaearth", name: "Mamaearth", industry: "consumer-goods", description: "Honasa's toxin-free D2C personal-care brand." },
  { slug: "media-net", name: "Media.net", industry: "technology", description: "Divyank Turakhia's contextual-advertising firm; sold 2016." },
  { slug: "nddb", name: "NDDB", industry: "agribusiness", description: "National Dairy Development Board; Verghese Kurien's cooperative-institution vehicle." },
  { slug: "nirma", name: "Nirma", industry: "consumer-goods", description: "Karsanbhai Patel's low-priced detergent and consumer-goods firm." },
  { slug: "nykaa", name: "Nykaa", industry: "e-commerce", description: "Falguni Nayar's inventory-led beauty e-commerce firm." },
  { slug: "ola", name: "Ola (ANI Technologies)", industry: "e-commerce", description: "Bhavish Aggarwal's ride-hailing platform." },
  { slug: "ola-electric", name: "Ola Electric", industry: "automotive", description: "Bhavish Aggarwal's electric-scooter venture." },
  { slug: "oyo", name: "OYO Rooms", industry: "hospitality", description: "Ritesh Aggarwal's hospitality-tech firm." },
  { slug: "parle-products", name: "Parle Products", industry: "consumer-goods", description: "Ramesh Chauhan's soft-drinks and biscuits house (Thums Up, Limca)." },
  { slug: "paytm", name: "Paytm (One97)", industry: "finance", description: "Vijay Shekhar Sharma's payments and financial-services brand." },
  { slug: "paytm-payments-bank", name: "Paytm Payments Bank", industry: "finance", description: "Paytm's RBI-regulated payments bank; subject to 2022-24 restrictions." },
  { slug: "phonepe", name: "PhonePe", industry: "finance", description: "Sameer Nigam's UPI payments platform." },
  { slug: "reliance-industries", name: "Reliance Industries", industry: "energy", description: "Reliance group holding; refining, petrochemicals, telecom and retail." },
  { slug: "reliance-jio", name: "Reliance Jio", industry: "telecom", description: "Reliance's telecom arm; launched 2016 with free-data pricing." },
  { slug: "reliance-retail", name: "Reliance Retail", industry: "retail", description: "Reliance's retail arm; India's largest by footprint." },
  { slug: "satyam", name: "satyam", industry: "industrials" },
  { slug: "serum-institute", name: "Serum Institute of India", industry: "pharmaceuticals", description: "World's largest vaccine manufacturer by dose volume." },
  { slug: "snapdeal", name: "Snapdeal", industry: "e-commerce", description: "Bahl-Bansal marketplace; pivoted to value commerce post-2017." },
  { slug: "sterlite", name: "Sterlite Industries", industry: "steel-and-metals", description: "Anil Agarwal's first listed Indian mining vehicle." },
  { slug: "swiggy", name: "Swiggy", industry: "e-commerce", description: "Majety-Reddy food-delivery and quick-commerce platform." },
  { slug: "tata-consultancy-services", name: "Tata Consultancy Services", industry: "technology", description: "Tata group IT-services arm; India's largest offshore services firm." },
  { slug: "tata-group", name: "Tata Group", industry: "industrials", description: "India's largest conglomerate by scale; trust-owned holding structure." },
  { slug: "tata-motors", name: "Tata Motors", industry: "automotive", description: "Tata group automaker; commercial vehicles, passenger cars and JLR." },
  { slug: "tata-steel", name: "Tata Steel", industry: "steel-and-metals", description: "Tata group steelmaker; India's oldest integrated steel plant." },
  { slug: "uidai", name: "UIDAI / Aadhaar", industry: "technology", description: "The Unique Identification Authority of India; issuer of the Aadhaar identity." },
  { slug: "vedanta", name: "Vedanta Limited", industry: "steel-and-metals", description: "Anil Agarwal's diversified mining-and-metals operating company." },
  { slug: "vedanta-resources", name: "Vedanta Resources", industry: "steel-and-metals", description: "Anil Agarwal's London-listed holding company, later re-domiciled." },
  { slug: "vodafone-idea", name: "Vodafone Idea", industry: "telecom", description: "Idea Cellular-Vodafone India merged telecom operator." },
  { slug: "walmart-india", name: "Walmart India", industry: "retail", description: "Acquirer of Flipkart (2018); the local cash-and-carry operator." },
  { slug: "wipro", name: "Wipro", industry: "technology", description: "Premji-chaired IT-services firm, pivoted from vegetable-oil trading." },
  { slug: "zerodha", name: "Zerodha", industry: "finance", description: "Kamath brothers' bootstrapped discount brokerage." },
  { slug: "zomato", name: "Zomato / Eternal", industry: "e-commerce", description: "Deepinder Goyal's food-delivery and quick-commerce firm." },
  { slug: "alibaba", name: "Alibaba Group", canonicalName: "Alibaba Group Holding Limited", ticker: "BABA", industry: "technology", description: "Chinese e-commerce and cloud conglomerate founded by Jack Ma." },
  { slug: "ant-group", name: "Ant Group", canonicalName: "Ant Group Co., Ltd.", industry: "finance", description: "Alibaba fintech affiliate whose 2020 IPO was suspended days before listing." },
  { slug: "tencent", name: "Tencent", canonicalName: "Tencent Holdings Ltd.", ticker: "0700-HK", industry: "technology", description: "Chinese internet and gaming conglomerate; WeChat parent." },
  { slug: "bytedance", name: "ByteDance", canonicalName: "ByteDance Ltd.", industry: "technology", description: "Beijing-based parent of TikTok and Douyin, founded by Zhang Yiming." },
  { slug: "tiktok", name: "TikTok", canonicalName: "TikTok", industry: "technology", description: "Short-video app operated outside China by ByteDance; subject of US divestiture pressure." },
  { slug: "baidu", name: "Baidu", canonicalName: "Baidu, Inc.", ticker: "BIDU", industry: "technology", description: "Chinese search engine and AI company founded by Robin Li." },
  { slug: "sohu", name: "Sohu", canonicalName: "Sohu.com Inc.", ticker: "SOHU", industry: "technology", description: "Early Chinese internet portal founded by Zhang Chaoyang; listed on NASDAQ in 2000." },
  { slug: "kuaishou", name: "Kuaishou", canonicalName: "Kuaishou Technology", ticker: "1024-HK", industry: "technology", description: "Short-video platform whose founder Su Hua grew it from a GIF tool." },
  { slug: "yy", name: "YY", canonicalName: "JOYY Inc.", ticker: "YY", industry: "technology", description: "Live-streaming platform founded by Li Xueling." },
  { slug: "qihoo-360", name: "Qihoo 360", canonicalName: "360 Security Technology", ticker: "601360-SS", industry: "technology", description: "Chinese internet security and search company founded by Zhou Hongyi." },
  { slug: "meituan", name: "Meituan", canonicalName: "Meituan", ticker: "3690-HK", industry: "technology", description: "Chinese on-demand services super-app founded by Wang Xing." },
  { slug: "deepseek", name: "DeepSeek", canonicalName: "DeepSeek", industry: "technology", description: "Chinese AI lab founded by Liang Wenfeng; released the R1 open-weights reasoning model in 2025." },
  { slug: "01-ai", name: "01.AI", canonicalName: "01.AI", industry: "technology", description: "Chinese AI startup founded by Kai-Fu Lee." },
  { slug: "high-flyer", name: "High-Flyer", canonicalName: "High-Flyer (Hangzhou)", industry: "technology", description: "Quant fund and AI compute sponsor that incubated DeepSeek." },
  { slug: "sinovation-ventures", name: "Sinovation Ventures", canonicalName: "Sinovation Ventures", industry: "asset-management", description: "Early-stage Chinese VC founded by Kai-Fu Lee." },
  { slug: "kingsoft", name: "Kingsoft", canonicalName: "Kingsoft Corporation", ticker: "3888-HK", industry: "technology", description: "Chinese software company where Lei Jun rose to CEO and led its 2007 IPO." },
  { slug: "kingsoft-office", name: "Kingsoft Office", canonicalName: "Kingsoft Office Software", ticker: "688561-SS", industry: "technology", description: "WPS Office software spun out of Kingsoft; Lei Jun chairs." },
  { slug: "netease", name: "NetEase", canonicalName: "NetEase, Inc.", ticker: "NTES", industry: "technology", description: "Chinese gaming and internet company founded by Ding Lei." },
  { slug: "shanda", name: "Shanda", canonicalName: "Shanda Interactive Entertainment", industry: "technology", description: "Early Chinese gaming and internet conglomerate founded by Chen Tianqiao." },
  { slug: "joyo", name: "Joyo", canonicalName: "Joyo.com", industry: "technology", description: "Chinese e-commerce pioneer founded in 2000; acquired by Amazon in 2004." },
  { slug: "wali-internet", name: "Wali Internet", canonicalName: "Wali Internet", industry: "technology", description: "Beijing internet company whose founder Lai Meisong later built ZTO Express." },
  { slug: "lenovo", name: "Lenovo", canonicalName: "Lenovo Group Limited", ticker: "0992-HK", industry: "technology", description: "Chinese PC and server maker spun out of Legend Holdings." },
  { slug: "legend-holdings", name: "Legend Holdings", canonicalName: "Legend Holdings Ltd.", ticker: "3396-HK", industry: "finance", description: "Diversified Chinese holding company founded by Liu Chuanzhi; parent of Lenovo." },
  { slug: "huawei", name: "Huawei", canonicalName: "Huawei Technologies Co., Ltd.", industry: "technology", description: "Shenzhen-based telecom equipment and consumer electronics giant founded by Ren Zhengfei." },
  { slug: "pop-mart", name: "Pop Mart", canonicalName: "Pop Mart International", ticker: "9992-HK", industry: "consumer-goods", description: "Chinese collectible toy retailer founded by Wang Ning." },
  { slug: "xiaomi", name: "Xiaomi", canonicalName: "Xiaomi Corporation", ticker: "1810-HK", industry: "technology", description: "Chinese smartphone and IoT maker; founder Lei Jun launched an EV line in 2024." },
  { slug: "nio", name: "NIO", canonicalName: "NIO Inc.", ticker: "NIO", industry: "automotive", description: "Chinese EV maker founded by William Li." },
  { slug: "li-auto", name: "Li Auto", canonicalName: "Li Auto, Inc.", ticker: "LI", industry: "automotive", description: "Chinese EV maker founded by Li Xiang, focused on extended-range SUVs." },
  { slug: "xpeng", name: "XPeng", canonicalName: "XPeng Inc.", ticker: "XPEV", industry: "automotive", description: "Chinese EV maker founded by He Xiaopeng." },
  { slug: "great-wall-motor", name: "Great Wall Motor", canonicalName: "Great Wall Motor Co., Ltd.", ticker: "601633-SS", industry: "automotive", description: "Baoding-based automaker founded by Wei Jianjun." },
  { slug: "wanxiang-group", name: "Wanxiang Group", canonicalName: "Wanxiang Group", industry: "automotive", description: "Chinese auto-parts conglomerate founded by Lu Guanqiu." },
  { slug: "pirelli", name: "Pirelli", canonicalName: "Pirelli & C. S.p.A.", ticker: "PIRC-MI", industry: "automotive", description: "Italian tire maker acquired by Chemchina in 2015." },
  { slug: "suntech-power", name: "Suntech Power", canonicalName: "Suntech Power Holdings", ticker: "STP", industry: "energy", description: "Chinese solar panel maker founded by Shi Zhengrong; once the world's largest." },
  { slug: "gree-electric", name: "Gree Electric", canonicalName: "Gree Electric Appliances", ticker: "000651-SZ", industry: "consumer-goods", description: "Zhuhai-based air conditioner maker chaired by Dong Mingzhu." },
  { slug: "haier", name: "Haier", canonicalName: "Haier Smart Home", ticker: "600690-SS", industry: "consumer-goods", description: "Qingdao-based white-goods multinational; Zhang Ruimin's career company." },
  { slug: "nongfu-spring", name: "Nongfu Spring", canonicalName: "Nongfu Spring Co., Ltd.", ticker: "9633-HK", industry: "beverages", description: "Chinese bottled water and beverage company founded by Zhong Shanshan." },
  { slug: "wahaha", name: "Wahaha", canonicalName: "Hangzhou Wahaha Group", industry: "consumer-goods", description: "Chinese beverage and food company founded by Zong Qinghou." },
  { slug: "muyuan-foods", name: "Muyuan Foods", canonicalName: "Muyuan Foodstuff Co.", ticker: "002714-SZ", industry: "consumer-goods", description: "Chinese pig-farming company founded by Qin Yinglin." },
  { slug: "haidilao", name: "Haidilao", canonicalName: "Haidilao International", ticker: "6862-HK", industry: "restaurants", description: "Chinese hotpot chain founded by Zhang Yong; known for service culture." },
  { slug: "mindray", name: "Mindray", canonicalName: "Mindray Medical International", ticker: "300760-SZ", industry: "healthcare", description: "Shenzhen medical device maker founded by Li Xiting." },
  { slug: "wantai-biological", name: "Wantai Biological", canonicalName: "Beijing Wantai Biological Pharmacy", industry: "healthcare", description: "Vaccine and diagnostic reagent company; Zhong Shanshan chairs." },
  { slug: "fosun-international", name: "Fosun International", canonicalName: "Fosun International Limited", ticker: "0656-HK", industry: "finance", description: "Chinese conglomerate founded by Guo Guangchang." },
  { slug: "evergrande", name: "Evergrande", canonicalName: "China Evergrande Group", ticker: "3333-HK", industry: "finance", description: "Guangzhou property developer founded by Xu Jiayin; defaulted in 2021." },
  { slug: "country-garden", name: "Country Garden", canonicalName: "Country Garden Holdings", ticker: "2007-HK", industry: "finance", description: "Foshan property developer chaired by Yang Guoqiang; tipped into distress in 2023." },
  { slug: "dalian-wanda-group", name: "Dalian Wanda Group", canonicalName: "Dalian Wanda Group", industry: "finance", description: "Dalian property and cinema conglomerate founded by Wang Jianlin." },
  { slug: "soho-china", name: "SOHO China", canonicalName: "SOHO China Limited", ticker: "0410-HK", industry: "finance", description: "Beijing commercial property developer founded by Pan Shiyi and Zhang Xin." },
  { slug: "rong-family-corporation", name: "Rong Family Corporation", canonicalName: "Rong Family Corporation", industry: "finance", description: "Pre-1949 Chinese industrial empire built by Rong Zongjing and Rong Desheng." },
  { slug: "fuyao-glass", name: "Fuyao Glass", canonicalName: "Fuyao Glass Industry Group", ticker: "600660-SS", industry: "industrials", description: "Fuqing automotive glass maker founded by Cao Dewang; largest of its kind globally." },
  { slug: "sf-express", name: "SF Express", canonicalName: "S.F. Holding", ticker: "002352-SZ", industry: "industrials", description: "Chinese courier founded by Wang Wei; the country's largest express delivery firm." },
  { slug: "zto-express", name: "ZTO Express", canonicalName: "ZTO Express (Cayman) Inc.", ticker: "ZTO", industry: "industrials", description: "Chinese parcel delivery company founded by Lai Meisong." },
  { slug: "nine-dragons-paper", name: "Nine Dragons Paper", canonicalName: "Nine Dragons Paper Holdings", ticker: "2689-HK", industry: "industrials", description: "Containerboard maker founded by Zhang Yin; one of Asia's largest paper companies." },
  { slug: "dasheng-cotton-mill", name: "Dasheng Cotton Mill", canonicalName: "Dasheng Cotton Mill", industry: "industrials", description: "Late-Qing textile mill founded by Zhang Jian in 1899; early Chinese industrialization." },
  { slug: "hongsheng-match-company", name: "Hongsheng Match Company", canonicalName: "Hongsheng Match Company", industry: "industrials", description: "Early 20th-century Chinese match manufacturer founded by Liu Hongsheng." },
  { slug: "east-hope-group", name: "East Hope Group", canonicalName: "East Hope Group", industry: "industrials", description: "Shanghai diversified industrial group founded by Liu Yongxing; alumina and agribusiness." },
  { slug: "new-hope-group", name: "New Hope Group", canonicalName: "New Hope Group", industry: "industrials", description: "Sichuan agribusiness conglomerate founded by Liu Yonghao." },
  { slug: "chemchina", name: "ChemChina", canonicalName: "China National Chemical Corporation", industry: "industrials", description: "State-owned chemical group; acquired Pirelli and Syngenta." },
  { slug: "syngenta", name: "Syngenta", canonicalName: "Syngenta AG", industry: "industrials", description: "Swiss agribusiness acquired by Chemchina in 2017." },
  { slug: "new-oriental", name: "New Oriental", canonicalName: "New Oriental Education & Technology Group", ticker: "EDU", industry: "consumer-goods", description: "Chinese education services company founded by Yu Minhong; listed on NYSE in 2006." },
  { slug: "didi", name: "DiDi", canonicalName: "DiDi Global Inc.", ticker: "DIDIY", industry: "technology", description: "Chinese ride-hailing platform founded by Cheng Wei; suspended US IPO under regulatory pressure in 2021." },
  { slug: "pdd-holdings", name: "PDD Holdings", canonicalName: "PDD Holdings Inc.", ticker: "PDD", industry: "retail", description: "Multinational commerce group; parent of Pinduoduo and Temu." },
  { slug: "pinduoduo", name: "Pinduoduo", canonicalName: "Pinduoduo", industry: "retail", description: "Chinese group-buying e-commerce platform founded by Colin Huang." },
  { slug: "temu", name: "Temu", canonicalName: "Temu", industry: "retail", description: "PDD's cross-border discount marketplace launched in 2022." },
  { slug: "jd-com", name: "JD.com", canonicalName: "JD.com, Inc.", ticker: "JD", industry: "retail", description: "Chinese direct-sale e-commerce platform founded by Richard Liu." },
];

export const THEMES = [
  { slug: "moats", name: "Economic Moats", description: "Durable advantages that keep competitors from destroying returns." },
  { slug: "capital-allocation", name: "Capital Allocation", description: "How owners decide where retained earnings go next." },
  { slug: "valuation", name: "Valuation", description: "Estimating what a business is actually worth." },
  { slug: "margin-of-safety", name: "Margin of Safety", description: "Buying significantly below estimated value to absorb error." },
  { slug: "circle-of-competence", name: "Circle of Competence", description: "Knowing which businesses you can genuinely evaluate." },
  { slug: "compounding", name: "Compounding", description: "The mathematics and psychology of exponential growth over time." },
  { slug: "risk-management", name: "Risk Management", description: "Avoiding permanent loss of capital above all." },
  { slug: "inflation", name: "Inflation", description: "How rising prices tax businesses and investors differently." },
  { slug: "market-psychology", name: "Market Psychology", description: "Crowd emotion as the engine of mispricing." },
  { slug: "contrarianism", name: "Contrarianism", description: "Acting against consensus when price and value diverge." },
  { slug: "long-term-ownership", name: "Long-Term Ownership", description: "Holding great assets for decades rather than trading them." },
  { slug: "management-quality", name: "Management Quality", description: "Judging the people running the business." },
  { slug: "corporate-governance", name: "Corporate Governance", description: "Structures that align managers with owners." },
  { slug: "diversification", name: "Diversification", description: "Spreading bets versus concentrating conviction." },
  { slug: "index-investing", name: "Index Investing", description: "Owning the market at minimal cost instead of picking winners." },
  { slug: "credit-cycles", name: "Credit Cycles", description: "The pendulum between easy money and credit drought." },
  { slug: "liquidity", name: "Liquidity", description: "Cash readiness as strategic optionality." },
  { slug: "volatility-vs-risk", name: "Volatility vs Risk", description: "Why price movement is not the same as permanent loss." },
  { slug: "price-versus-value", name: "Price vs Value", description: "The gap between what you pay and what you get." },
  { slug: "patience", name: "Patience", description: "Waiting for fat pitches instead of swinging constantly." },
  { slug: "mistakes-and-learning", name: "Mistakes & Learning", description: "Documented errors and what they taught." },
  { slug: "insurance-economics", name: "Insurance Economics", description: "Float, underwriting discipline, and combined ratios." },
  { slug: "second-level-thinking", name: "Second-Level Thinking", description: "Asking what is priced in, not just what is true." },
  { slug: "opportunity-cost", name: "Opportunity Cost", description: "Every buy is measured against the next best alternative." },
  { slug: "cash-reserves", name: "Cash Reserves", description: "Defensive cash as dry powder for crises." },
  { slug: "bubbles-and-crashes", name: "Bubbles & Crashes", description: "Manias, crashes, and their repeating anatomy." },
  { slug: "shareholder-orientation", name: "Shareholder Orientation", description: "Treating shareholders as partners rather than marks." },
  { slug: "position-sizing", name: "Position Sizing", description: "How much conviction deserves how much capital." },
  { slug: "debt-discipline", name: "Debt Discipline", description: "Leverage as the classic path to ruin." },
  { slug: "quality-businesses", name: "Quality Businesses", description: "Wonderful franchises earning high returns on capital." },
  { slug: "turnarounds", name: "Turnarounds", description: "Fixing or riding cyclically depressed situations." },
  { slug: "earnings-growth", name: "Earnings Growth", description: "Growth rates as the engine of long-run value." },
  { slug: "dividends-policy", name: "Dividend Policy", description: "When distributing cash creates versus destroys value." },
  { slug: "bootstrapping", name: "Bootstrapping", description: "Building without external equity; founder-funded growth." },
  { slug: "brand-building", name: "Brand Building", description: "Constructing durable consumer or corporate brands." },
  { slug: "capital-allocation-discipline", name: "Capital Allocation Discipline", description: "The rigour of deploying capital only where it earns above cost." },
  { slug: "cash-flow-discipline", name: "Cash-Flow Discipline", description: "Managing cash generation and burn as the primary scorecard." },
  { slug: "concentration", name: "concentration" },
  { slug: "conglomerate-building", name: "Conglomerate Building", description: "Assembling multi-business groups under one house." },
  { slug: "cooperative-model", name: "Cooperative Model", description: "Producer- or member-owned enterprise structures." },
  { slug: "covid-19-2020", name: "covid-19-2020" },
  { slug: "crisis-management", name: "Crisis Management", description: "Leading through governance, market or regulatory shocks." },
  { slug: "cyclical-businesses", name: "cyclical-businesses" },
  { slug: "d2c-economics", name: "D2C Economics", description: "Unit economics of selling direct to the consumer online." },
  { slug: "deep-tech-bets", name: "Deep-Tech Bets", description: "Backing research-heavy, long-horizon technology." },
  { slug: "disruptive-pricing", name: "Disruptive Pricing", description: "Using price as the wedge to reshape a market." },
  { slug: "distribution-moats", name: "Distribution Moats", description: "Reach and last-mile density as a durable advantage." },
  { slug: "economic-moats", name: "economic-moats" },
  { slug: "esops-and-ownership", name: "ESOPs & Ownership", description: "Equity-based compensation and ownership culture." },
  { slug: "ev-transition", name: "EV Transition", description: "The shift from internal-combustion to electric drivetrains." },
  { slug: "family-business-stewardship", name: "Family-Business Stewardship", description: "Holding and transferring groups across generations." },
  { slug: "fintech-regulation", name: "Fintech Regulation", description: "The regulatory perimeter around digital financial services." },
  { slug: "founder-ceo-succession", name: "Founder-CEO Succession", description: "Transitioning from founder to professional chief executive." },
  { slug: "founder-culture", name: "Founder Culture", description: "The operating style and myths a founder imprints." },
  { slug: "founder-exits", name: "Founder Exits", description: "Departures, sales and handovers by the founding promoter." },
  { slug: "franchising-model", name: "Franchising Model", description: "Scaling via franchisee-operated outlets." },
  { slug: "fraud-and-collapse", name: "Fraud & Collapse", description: "Governance failures that end in insolvency or prosecution." },
  { slug: "frugal-innovation", name: "Frugal Innovation", description: "Engineering low-cost products for constrained markets." },
  { slug: "globalization", name: "Globalization", description: "Cross-border expansion and overseas acquisition." },
  { slug: "governance", name: "Governance", description: "Board, disclosure and control architecture of a firm." },
  { slug: "government-relations", name: "Government Relations", description: "Managing the policy and state interface." },
  { slug: "growth-vs-value", name: "growth-vs-value" },
  { slug: "infrastructure-building", name: "Infrastructure Building", description: "Ports, power, telecom and logistics as national capacity." },
  { slug: "inventory-and-working-capital", name: "Inventory & Working Capital", description: "Turns, stock cycles and the cash tied up in operations." },
  { slug: "ipo-strategy", name: "IPO Strategy", description: "The timing, pricing and narrative of going public." },
  { slug: "j-curve-investing", name: "J-Curve Investing", description: "Returns trajectory that dips before climbing." },
  { slug: "joint-ventures", name: "Joint Ventures", description: "Partnered entities sharing capital and control." },
  { slug: "liberalization-1991", name: "liberalization-1991" },
  { slug: "license-raj-strategy", name: "Licence-Raj Strategy", description: "Operating under India's pre-1991 permit-and-quota regime." },
  { slug: "licensing-deals", name: "Licensing Deals", description: "Granting or taking licenses for brands, technology or distribution." },
  { slug: "long-horizon", name: "long-horizon" },
  { slug: "m-and-a-acquisitions", name: "M&A / Acquisitions", description: "Buying businesses to consolidate, enter or exit markets." },
  { slug: "mistakes", name: "mistakes" },
  { slug: "network-effects", name: "Network Effects", description: "Value that grows with the number of participants." },
  { slug: "omnichannel-strategy", name: "Omnichannel Strategy", description: "Integrating offline and online commerce." },
  { slug: "outsourcing-strategy", name: "Outsourcing Strategy", description: "Contracting out network, IT or operations to scale." },
  { slug: "platform-economics", name: "Platform Economics", description: "Multi-sided markets that intermediate participants." },
  { slug: "policy-betting", name: "Policy Betting", description: "Positioning ahead of expected state action." },
  { slug: "price-war-strategy", name: "Price-War Strategy", description: "Using aggressive pricing to restructure a market." },
  { slug: "pricing-power", name: "pricing-power" },
  { slug: "professionalization-vs-promoter", name: "Professionalization vs Promoter", description: "The tension between hired managers and promoter owners." },
  { slug: "promoter-equity-dilution", name: "Promoter Equity Dilution", description: "The founder's stake shrinking through funding rounds." },
  { slug: "public-infrastructure-bets", name: "Public-Infrastructure Bets", description: "Building identity, payments or data rails as public goods." },
  { slug: "r-and-d-and-innovation", name: "R&D and Innovation", description: "Research spending as a long-cycle investment." },
  { slug: "regulatory-navigation", name: "Regulatory Navigation", description: "Operating within and around sectoral rules." },
  { slug: "scale-before-profitability", name: "Scale Before Profitability", description: "Prioritising reach over margin in early phases." },
  { slug: "scale-economics", name: "Scale Economics", description: "Unit-cost advantages that compound with volume." },
  { slug: "strategic-vs-financial-investor", name: "Strategic vs Financial Investor", description: "The different logic of operating and purely financial buyers." },
  { slug: "succession-planning", name: "Succession Planning", description: "Designing the next generation of leadership and ownership." },
  { slug: "technology-pivot", name: "Technology Pivot", description: "Re-platforming a business around new technology." },
  { slug: "turnaround-management", name: "Turnaround Management", description: "Restoring a distressed business to viability." },
  { slug: "two-sided-markets", name: "Two-Sided Markets", description: "Platforms connecting distinct participant groups." },
  { slug: "unit-economics", name: "Unit Economics", description: "Per-transaction economics of a business model." },
  { slug: "vc-vs-bootstrapping", name: "VC vs Bootstrapping", description: "The trade-off between outside capital and founder control." },
  { slug: "vertical-integration", name: "Vertical Integration", description: "Owning upstream or downstream stages of the chain." },
  { slug: "white-space-creation", name: "White-Space Creation", description: "Entering unoccupied categories between existing ones." },
  { slug: "founding-and-origins", name: "Founding and Origins", description: "How a business was started, the founding insight, and the conditions that shaped its first chapter." },
  { slug: "conglomerate-strategy", name: "Conglomerate Strategy", description: "Building or holding a multi-industry group whose diversity is itself the strategy." },
  { slug: "crisis-response", name: "Crisis Response", description: "How leaders act when capital markets, regulators, or operations turn hostile." },
  { slug: "business-philosophy", name: "Business Philosophy", description: "The stated principles a founder or operator claims to run by." },
  { slug: "industry-transition", name: "Industry Transition", description: "Sector-wide shifts (energy, transport, media) that move value from incumbents to newcomers." },
  { slug: "innovation", name: "Innovation", description: "New products, processes, or business models that change how an industry works." },
  { slug: "international-expansion", name: "International Expansion", description: "Crossing borders for customers, capital, or supply chain." },
  { slug: "ipo-and-capital-markets", name: "IPO and Capital Markets", description: "Going public, raising capital, and the discipline of public-market scrutiny." },
  { slug: "leadership-transition", name: "Leadership Transition", description: "Handing operating control from founder to successor or next-generation management." },
  { slug: "philanthropy", name: "Philanthropy", description: "Founders giving wealth back through foundations, pledges, or direct gifts." },
  { slug: "regulatory-environment", name: "Regulatory Environment", description: "How statute, agency rule-making, and enforcement shape an industry." },
  { slug: "research-and-development", name: "Research and Development", description: "Sustained spending to push a technical frontier." },
  { slug: "bankruptcy-and-restructuring", name: "Bankruptcy and Restructuring", description: "Distress workouts, debt restructurings, and the lessons of insolvency." },
];

export const CONCEPTS = [
  { slug: "mr-market", name: "Mr. Market", description: "Graham's manic-depressive partner who offers prices daily." },
  { slug: "owner-earnings", name: "Owner Earnings", description: "Buffett's measure of distributable cash a business truly produces." },
  { slug: "look-through-earnings", name: "Look-Through Earnings", description: "Attributing retained earnings of investees to the owner." },
  { slug: "float", name: "Float", description: "Money held between premium collection and claim payment." },
  { slug: "dollar-cost-averaging", name: "Dollar-Cost Averaging", description: "Investing fixed sums at intervals regardless of price." },
  { slug: "mean-reversion", name: "Mean Reversion", description: "Extreme results tend to pull back toward averages." },
  { slug: "asymmetric-payoffs", name: "Asymmetric Payoffs", description: "Structuring bets where upside dwarfs downside." },
  { slug: "network-effects", name: "Network Effects", description: "Products that gain value as more people use them." },
  { slug: "switching-costs", name: "Switching Costs", description: "Friction that keeps customers from leaving." },
  { slug: "brand-equity", name: "Brand Equity", description: "The pricing power embedded in a trusted name." },
  { slug: "cost-advantage", name: "Cost Advantage", description: "Being structurally the cheapest operator wins markets." },
  { slug: "survivorship", name: "Survivorship", description: "Avoiding ruin is the precondition of compounding." },
  { slug: "cyclical-recovery", name: "Cyclical Recovery", description: "Positioning for the turn of supply-demand cycles." },
  { slug: "time-horizon", name: "Time Horizon", description: "Longer views convert noise into signal." },
  { slug: "scuttlebutt", name: "Scuttlebutt", description: "Fisher's method: gathering insight from customers, suppliers, and employees rather than filings alone." },
  { slug: "growth-runway", name: "Growth Runway", description: "The capacity of a business to compound sales for years before maturity." },
  { slug: "greenmail", name: "Greenmail", description: "1980s practice of buying back a raider's stake at a premium to end a takeover threat." },
  { slug: "proxy-fight", name: "Proxy Fight", description: "Campaign to win shareholder votes and replace a board without owning the company." },
  { slug: "leveraged-buyout", name: "Leveraged Buyout", description: "Acquiring a company using its own balance sheet as collateral." },
  { slug: "bootstrapped-profitability", name: "Bootstrapped Profitability", description: "Reaching profit without raising external equity." },
  { slug: "bootstrapping", name: "Bootstrapping", description: "Self-funding growth from operations rather than equity." },
  { slug: "cash-flow-discipline", name: "Cash-Flow Discipline", description: "Keeping cash generation ahead of spend." },
  { slug: "contract-manufacturing", name: "Contract Manufacturing", description: "Producing for brands under third-party agreements." },
  { slug: "cooperative-ownership", name: "Cooperative Ownership", description: "Members owning the enterprise through the cooperative." },
  { slug: "esops-and-ownership", name: "ESOPs & Ownership", description: "Employee stock plans aligning staff with equity holders." },
  { slug: "founder-ceo-succession", name: "Founder-CEO Succession", description: "The transition from founder to a hired chief executive." },
  { slug: "franchising-model", name: "Franchising Model", description: "Outlets operated by franchisees under a brand." },
  { slug: "holding-company-structure", name: "Holding Company Structure", description: "A parent holding stakes in operating businesses." },
  { slug: "j-curve-investing", name: "J-Curve Investing", description: "The early-dip-then-rise return shape of funds." },
  { slug: "joint-ventures", name: "Joint Ventures", description: "Entities owned jointly by two or more parents." },
  { slug: "licensing-deals", name: "Licensing Deals", description: "License grants for brand, tech or distribution rights." },
  { slug: "m-and-a-acquisitions", name: "M&A / Acquisitions", description: "Acquisitions as a growth or consolidation lever." },
  { slug: "platform-economics", name: "Platform Economics", description: "Intermediation economics of multi-sided platforms." },
  { slug: "professional-ceo-handoff", name: "Professional CEO Handoff", description: "A non-family chief executive taking the operating role." },
  { slug: "promoter-equity", name: "Promoter Equity", description: "The founder group's controlling stake in a listed firm." },
  { slug: "promoter-equity-dilution", name: "Promoter Equity Dilution", description: "The founder stake shrinking across funding rounds." },
  { slug: "strategic-vs-financial-investor", name: "Strategic vs Financial Investor", description: "Operating buyer vs purely financial buyer logic." },
  { slug: "two-sided-markets", name: "Two-Sided Markets", description: "Platforms joining two distinct participant sides." },
  { slug: "unit-economics", name: "Unit Economics", description: "Per-order or per-customer profit maths." },
  { slug: "scale-economics", name: "Scale Economics", description: "Unit cost falling as volume rises." },
  { slug: "ecosystem-building", name: "Ecosystem Building", description: "Wiring suppliers, developers, or merchants into a shared infrastructure." },
  { slug: "first-mover-advantage", name: "First-Mover Advantage", description: "Early entry locking in brand, supply, or network before rivals arrive." },
  { slug: "founder-thesis", name: "Founder Thesis", description: "The concentrated bet a founder makes on a single product, market, or model." },
  { slug: "partnership-structure", name: "Partnership Structure", description: "Ownership design that aligns operators and capital over the long run." },
  { slug: "political-risk", name: "Political Risk", description: "Exposure to government action — regulation, sanction, or favor." },
  { slug: "regulatory-moat", name: "Regulatory Moat", description: "A license, permit, or rule set that keeps competitors out." },
  { slug: "capital-cycle", name: "Capital Cycle", description: "Industry capital flowing in until returns collapse, then retreating." },
];

export const EVENTS = [
  { slug: "great-financial-crisis", name: "Great Financial Crisis", date: "2008", description: "Global credit collapse centered on mortgage securitization." },
  { slug: "dot-com-crash", name: "Dot-Com Crash", date: "2000", description: "Collapse of the late-1990s internet equity mania." },
  { slug: "black-monday-1987", name: "Black Monday 1987", date: "1987-10-19", description: "22% single-day market decline." },
  { slug: "covid-crash", name: "COVID Crash", date: "2020-03", description: "Pandemic panic and fastest bear-market recovery on record." },
  { slug: "oil-shock-1973", name: "Oil Shock 1973", date: "1973", description: "Embargo-driven energy spike and stagflation era." },
  { slug: "nifty-fifty-era", name: "Nifty Fifty Era", date: "1972", description: "One-decision blue-chip mania preceding the 1973-74 bust." },
  { slug: "salomon-scandal", name: "Salomon Scandal", date: "1991", description: "Treasury auction violations that forced Buffett into interim chairmanship." },
  { slug: "ltcm-1998", name: "LTCM Collapse", date: "1998", description: "Hedge fund failure demonstrating leverage plus intelligence equals fragility." },
  { slug: "2022-rate-shock", name: "2022 Rate Shock", date: "2022", description: "Fastest tightening cycle in four decades repricing all assets." },
  { slug: "japan-bubble", name: "Japan Bubble", date: "1989", description: "Japanese asset bubble and multi-decade deflationary aftermath." },
  { slug: "savings-loan-crisis", name: "Savings & Loan Crisis", date: "1989", description: "Thrift-industry insolvencies from duration mismatch and fraud." },
  { slug: "2g-spectrum-scam", name: "2G Spectrum Scam", date: "2008-2012", description: "Allegations and court cases around 2G telecom licence allocation." },
  { slug: "byjus-collapse-2023", name: "BYJU'S Collapse", date: "2023-2024", description: "The valuation, governance and insolvency unravelling of BYJU'S." },
  { slug: "future-reliance-retail-dispute", name: "Future-Reliance Retail Dispute", date: "2020-2022", description: "The contested Future-Reliance retail transaction and its collapse into insolvency." },
  { slug: "hindenburg-adani-2023", name: "Hindenburg Report on Adani", date: "2023-01", description: "Short-seller report alleging leverage and disclosure issues at the Adani Group." },
  { slug: "jio-launch-2016", name: "Reliance Jio Launch", date: "2016-09", description: "Jio's free-data entry that restructured Indian telecom pricing." },
  { slug: "liberalization-1991", name: "1991 Liberalisation", date: "1991", description: "India's balance-of-payments crisis and the reforms that opened the economy." },
  { slug: "license-raj", name: "Licence Raj", date: "1951-1991", description: "India's pre-liberalisation permit-and-quota industrial regime." },
  { slug: "license-raj-strategy", name: "Licence-Raj Strategy", date: "1951-1991", description: "Operating tactics under the pre-1991 permit regime." },
  { slug: "paytm-rbi-clampdown-2022", name: "Paytm Payments Bank Clampdown", date: "2022-2024", description: "RBI restrictions on Paytm Payments Bank that restructured the firm's payments posture." },
  { slug: "satyam-fraud-2009", name: "Satyam Fraud", date: "2009-01", description: "Ramalinga Raju's confession to having falsified Satyam's accounts." },
  { slug: "2001-wto-accession", name: "China WTO Accession", date: "2001", description: "China joining the WTO opened its markets and supply chains to the world." },
  { slug: "2020-ant-ipo-suspension", name: "Ant Group IPO Suspension", date: "2020-11", description: "Chinese regulators pulled the Ant Group dual listing days after Jack Ma criticized them." },
  { slug: "2021-platform-regulation", name: "China Platform Regulation", date: "2021", description: "Beijing launched a wide-ranging antitrust and data campaign against large internet platforms." },
  { slug: "2021-didi-us-ipo-delisting", name: "Didi US IPO and Delisting", date: "2021-06", description: "Didi listed in New York over regulator objections and was ordered into a US delisting within months." },
  { slug: "2021-evergrande-default", name: "Evergrande Default", date: "2021-12", description: "Evergrande missed dollar-bond payments, signaling the end of the Chinese property super-cycle." },
  { slug: "2023-country-garden-distress", name: "Country Garden Distress", date: "2023-08", description: "Country Garden tipped into default risk, deepening the property-sector debt crisis." },
  { slug: "2025-deepseek-r1-release", name: "DeepSeek R1 Release", date: "2025-01", description: "DeepSeek released an open-weights reasoning model that re-priced assumptions about AI compute needs." },
];
