export type CompanyDef = {
  slug: string;
  name: string;
  canonicalName?: string;
  ticker?: string;
  industry: string;
  description: string;
};

export const INDUSTRIES = [
  { slug: "beverages", name: "Beverages" },
  { slug: "consumer-goods", name: "Consumer Goods" },
  { slug: "insurance", name: "Insurance" },
  { slug: "finance", name: "Financial Services" },
  { slug: "railroads", name: "Railroads" },
  { slug: "energy", name: "Energy & Utilities" },
  { slug: "technology", name: "Technology" },
  { slug: "confectionery", name: "Confectionery" },
  { slug: "asset-management", name: "Asset Management" },
  { slug: "automotive", name: "Automotive" },
  { slug: "healthcare", name: "Healthcare" },
  { slug: "restaurants", name: "Restaurants" },
  { slug: "retail", name: "Retail" },
  { slug: "media", name: "Media" },
  { slug: "industrials", name: "Industrials" },
];

export const COMPANIES: CompanyDef[] = [
  { slug: "coca-cola", name: "Coca-Cola", canonicalName: "The Coca-Cola Company", ticker: "KO", industry: "beverages", description: "Global beverage company; long-held Berkshire position and a recurring example of brand strength and pricing power." },
  { slug: "sees-candies", name: "See's Candies", canonicalName: "See's Candies, Inc.", industry: "confectionery", description: "West Coast confectioner whose acquisition taught Berkshire about brand power, pricing, and the nature of an economic moat." },
  { slug: "geico", name: "GEICO", canonicalName: "Government Employees Insurance Company", industry: "insurance", description: "Auto insurer Berkshire acquired in full; a recurring illustration of low-cost operator advantage and float." },
  { slug: "berkshire-hathaway", name: "Berkshire Hathaway", canonicalName: "Berkshire Hathaway Inc.", ticker: "BRK", industry: "finance", description: "Diversified holding company chaired by Warren Buffett; the reporting entity for the annual letters." },
  { slug: "american-express", name: "American Express", canonicalName: "American Express Company", ticker: "AXP", industry: "finance", description: "Payments network company; a long-held Berkshire investment discussed in the context of brand and network effects." },
  { slug: "wells-fargo", name: "Wells Fargo", canonicalName: "Wells Fargo & Company", ticker: "WFC", industry: "finance", description: "Banking company; historically a large Berkshire bank holding, later reduced." },
  { slug: "bnsf", name: "BNSF Railway", canonicalName: "BNSF Railway", industry: "railroads", description: "Class I freight railroad acquired by Berkshire; an example of durable infrastructure and capital intensity." },
  { slug: "berkshire-energy", name: "Berkshire Hathaway Energy", industry: "energy", description: "Regulated utility and energy business; illustrates long-horizon capital deployment." },
  { slug: "apple", name: "Apple", canonicalName: "Apple Inc.", ticker: "AAPL", industry: "technology", description: "Consumer technology company; Berkshire's largest reported equity holding in the 2010s–2020s." },
  { slug: "gillette", name: "Gillette", canonicalName: "The Gillette Company", industry: "consumer-goods", description: "Consumer products company later absorbed into Procter & Gamble; cited as a strong consumer brand." },
  { slug: "washington-post", name: "Washington Post", canonicalName: "The Washington Post Company", industry: "media", description: "Media company Berkshire held for decades; an early lesson in business economics before ownership." },
  { slug: "usair", name: "USAir", canonicalName: "US Airways Group, Inc.", industry: "industrials", description: "Airline preferred stake cited as a mistake where industry economics overwhelmed the security." },
  { slug: "salomon", name: "Salomon Brothers", canonicalName: "Salomon Inc.", industry: "finance", description: "Investment bank where Berkshire took a preferred stake amid the 1991 Treasury scandal." },
  { slug: "conocophillips", name: "ConocoPhillips", ticker: "COP", industry: "energy", description: "Energy company; Berkshire bought near the 2008 oil peak, later acknowledged as mistimed." },
  { slug: "ibm", name: "IBM", canonicalName: "International Business Machines", ticker: "IBM", industry: "technology", description: "Technology holding Berkshire entered in 2011 and exited by 2018; a documented learning experience." },
  { slug: "kraft-heinz", name: "Kraft Heinz", ticker: "KHC", industry: "consumer-goods", description: "Packaged-food combine formed in 2015 with Berkshire participation; discussed around goodwill write-downs." },
  { slug: "petrochina", name: "PetroChina", ticker: "PTR", industry: "energy", description: "Chinese oil major Buffett bought on intrinsic value in 2002-2007 and sold when price caught value." },
  { slug: "byd", name: "BYD", ticker: "BYDDY", industry: "automotive", description: "Chinese EV and battery maker; Munger championed the position for Berkshire in Asia." },
  { slug: "moodys", name: "Moody's", canonicalName: "Moody's Corporation", ticker: "MCO", industry: "finance", description: "Ratings agency; long Berkshire holding illustrating toll-booth economics." },
  { slug: "goldman-sachs", name: "Goldman Sachs", ticker: "GS", industry: "finance", description: "Bank that sold Berkshire preferred stock during the 2008 crisis at crisis terms." },
  { slug: "general-electric", name: "General Electric", ticker: "GE", industry: "industrials", description: "Industrial conglomerate; received Berkshire crisis-era preferred investment in 2008." },
  { slug: "freddie-mac", name: "Freddie Mac", industry: "finance", description: "Mortgage agency Buffett owned early, exited before losses; a case study in regulatory risk." },
  { slug: "johnson-johnson", name: "Johnson & Johnson", ticker: "JNJ", industry: "healthcare", description: "Healthcare company held by Berkshire during the 2000s as a quality consumer-staple analog." },
  { slug: "procter-gamble", name: "Procter & Gamble", ticker: "PG", industry: "consumer-goods", description: "Consumer staples giant acquired via Gillette merger; later exchanged for other holdings." },
  { slug: "vanguard", name: "Vanguard", industry: "asset-management", description: "Bogle-founded mutual structure credited with igniting low-cost index investing." },
  { slug: "fidelity-magellan", name: "Fidelity Magellan Fund", industry: "asset-management", description: "Peter Lynch's fund, whose 1977-1990 record underpins his public teachings." },
  { slug: "dunkin", name: "Dunkin'", industry: "restaurants", description: "Donut chain Lynch used to illustrate finding great stocks in everyday life." },
  { slug: "pepsi", name: "PepsiCo", ticker: "PEP", industry: "beverages", description: "Beverage-snack company appearing in Lynch's stories about institutional neglect of consumer winners." },
  { slug: "volvo", name: "Volvo", industry: "automotive", description: "Swedish automaker Lynch famously owned after researching its cars rather than Wall Street reports." },
  { slug: "fannie-mae", name: "Fannie Mae", industry: "finance", description: "Mortgage finance company Lynch held successfully before government conservatorship changed its nature." },
  { slug: "northern-pipeline", name: "Northern Pipeline", industry: "energy", description: "Standard Oil spinoff Graham mined for liquidation value in his 1920s hidden-value work." },
  { slug: "graham-newman", name: "Graham-Newman Corporation", industry: "asset-management", description: "Graham's investment partnership where Buffett trained before starting his own partnership." },
  { slug: "oaktree", name: "Oaktree Capital", industry: "asset-management", description: "Alternative investment firm Howard Marks co-founded; publisher of his client memos." },
  { slug: "toyota", name: "Toyota", ticker: "TM", industry: "automotive", description: "Automaker cited in quality-and-efficiency discussions across investor writings." },
  { slug: "gen-re", name: "General Re", industry: "insurance", description: "Reinsurer Berkshire acquired in 1998; underwriting discipline lessons followed." },
  { slug: "netjets", name: "NetJets", industry: "industrials", description: "Fractional jet ownership business acquired by Berkshire in 1998." },
  { slug: "helzberg", name: "Helzberg Diamonds", industry: "retail", description: "Jewelry retailer sold to Berkshire by its owner with a handshake deal." },
  { slug: "nebraska-furniture-mart", name: "Nebraska Furniture Mart", industry: "retail", description: "Rose Blumkin's Omaha furniture store; Berkshire's favorite story of operating excellence." },
  { slug: "jordans-furniture", name: "Jordan's Furniture", industry: "retail", description: "Massachusetts furniture retailer acquired by Berkshire in 1999." },
  { slug: "flight-safety", name: "FlightSafety International", industry: "industrials", description: "Aviation training company acquired by Berkshire; recurring quality-business example." },
];

export const THEMES = [
  { slug: "moats", name: "Economic Moats", description: "Durable advantages that keep competitors from destroying returns." },
  { slug: "capital-allocation", name: "Capital Allocation", description: "How owners decide where retained earnings go next." },
  { slug: "valuation", name: "Valuation", description: "Estimating what a business is actually worth." },
  { slug: "margin-of-safety", name: "Margin of Safety", description: "Buying significantly below estimated value to absorb error." },
  { slug: "circle-of-competence", name: "Circle of Competence", description: "Knowing which businesses you can genuinely evaluate." },
  { slug: "compounding", name: "Compounding", description: "The mathematics and psychology of exponential growth over time." },
  { slug: "risk-management", name: "Risk Management", description: "Avoiding permanent loss of capital above all." },
  { slug: "inflation", name: "Inflation", description: "How rising prices tax businesses and investors differently." },
  { slug: "market-psychology", name: "Market Psychology", description: "Crowd emotion as the engine of mispricing." },
  { slug: "contrarianism", name: "Contrarianism", description: "Acting against consensus when price and value diverge." },
  { slug: "long-term-ownership", name: "Long-Term Ownership", description: "Holding great assets for decades rather than trading them." },
  { slug: "management-quality", name: "Management Quality", description: "Judging the people running the business." },
  { slug: "corporate-governance", name: "Corporate Governance", description: "Structures that align managers with owners." },
  { slug: "diversification", name: "Diversification", description: "Spreading bets versus concentrating conviction." },
  { slug: "index-investing", name: "Index Investing", description: "Owning the market at minimal cost instead of picking winners." },
  { slug: "credit-cycles", name: "Credit Cycles", description: "The pendulum between easy money and credit drought." },
  { slug: "liquidity", name: "Liquidity", description: "Cash readiness as strategic optionality." },
  { slug: "volatility-vs-risk", name: "Volatility vs Risk", description: "Why price movement is not the same as permanent loss." },
  { slug: "price-versus-value", name: "Price vs Value", description: "The gap between what you pay and what you get." },
  { slug: "patience", name: "Patience", description: "Waiting for fat pitches instead of swinging constantly." },
  { slug: "mistakes-and-learning", name: "Mistakes & Learning", description: "Documented errors and what they taught." },
  { slug: "insurance-economics", name: "Insurance Economics", description: "Float, underwriting discipline, and combined ratios." },
  { slug: "second-level-thinking", name: "Second-Level Thinking", description: "Asking what is priced in, not just what is true." },
  { slug: "opportunity-cost", name: "Opportunity Cost", description: "Every buy is measured against the next best alternative." },
  { slug: "cash-reserves", name: "Cash Reserves", description: "Defensive cash as dry powder for crises." },
  { slug: "bubbles-and-crashes", name: "Bubbles & Crashes", description: "Manias, crashes, and their repeating anatomy." },
  { slug: "shareholder-orientation", name: "Shareholder Orientation", description: "Treating shareholders as partners rather than marks." },
  { slug: "position-sizing", name: "Position Sizing", description: "How much conviction deserves how much capital." },
  { slug: "debt-discipline", name: "Debt Discipline", description: "Leverage as the classic path to ruin." },
  { slug: "quality-businesses", name: "Quality Businesses", description: "Wonderful franchises earning high returns on capital." },
  { slug: "turnarounds", name: "Turnarounds", description: "Fixing or riding cyclically depressed situations." },
  { slug: "earnings-growth", name: "Earnings Growth", description: "Growth rates as the engine of long-run value." },
  { slug: "dividends-policy", name: "Dividend Policy", description: "When distributing cash creates versus destroys value." },
];

export const CONCEPTS = [
  { slug: "mr-market", name: "Mr. Market", description: "Graham's manic-depressive partner who offers prices daily." },
  { slug: "owner-earnings", name: "Owner Earnings", description: "Buffett's measure of distributable cash a business truly produces." },
  { slug: "look-through-earnings", name: "Look-Through Earnings", description: "Attributing retained earnings of investees to the owner." },
  { slug: "float", name: "Float", description: "Money held between premium collection and claim payment." },
  { slug: "dollar-cost-averaging", name: "Dollar-Cost Averaging", description: "Investing fixed sums at intervals regardless of price." },
  { slug: "mean-reversion", name: "Mean Reversion", description: "Extreme results tend to pull back toward averages." },
  { slug: "asymmetric-payoffs", name: "Asymmetric Payoffs", description: "Structuring bets where upside dwarfs downside." },
  { slug: "network-effects", name: "Network Effects", description: "Products that gain value as more people use them." },
  { slug: "switching-costs", name: "Switching Costs", description: "Friction that keeps customers from leaving." },
  { slug: "brand-equity", name: "Brand Equity", description: "The pricing power embedded in a trusted name." },
  { slug: "cost-advantage", name: "Cost Advantage", description: "Being structurally the cheapest operator wins markets." },
  { slug: "survivorship", name: "Survivorship", description: "Avoiding ruin is the precondition of compounding." },
  { slug: "cyclical-recovery", name: "Cyclical Recovery", description: "Positioning for the turn of supply-demand cycles." },
  { slug: "time-horizon", name: "Time Horizon", description: "Longer views convert noise into signal." },
];

export const EVENTS = [
  { slug: "great-financial-crisis", name: "Great Financial Crisis", date: "2008", description: "Global credit collapse centered on mortgage securitization." },
  { slug: "dot-com-crash", name: "Dot-Com Crash", date: "2000", description: "Collapse of the late-1990s internet equity mania." },
  { slug: "black-monday-1987", name: "Black Monday 1987", date: "1987-10-19", description: "22% single-day market decline." },
  { slug: "covid-crash", name: "COVID Crash", date: "2020-03", description: "Pandemic panic and fastest bear-market recovery on record." },
  { slug: "oil-shock-1973", name: "Oil Shock 1973", date: "1973", description: "Embargo-driven energy spike and stagflation era." },
  { slug: "nifty-fifty-era", name: "Nifty Fifty Era", date: "1972", description: "One-decision blue-chip mania preceding the 1973-74 bust." },
  { slug: "salomon-scandal", name: "Salomon Scandal", date: "1991", description: "Treasury auction violations that forced Buffett into interim chairmanship." },
  { slug: "ltcm-1998", name: "LTCM Collapse", date: "1998", description: "Hedge fund failure demonstrating leverage plus intelligence equals fragility." },
  { slug: "2022-rate-shock", name: "2022 Rate Shock", date: "2022", description: "Fastest tightening cycle in four decades repricing all assets." },
  { slug: "japan-bubble", name: "Japan Bubble", date: "1989", description: "Japanese asset bubble and multi-decade deflationary aftermath." },
  { slug: "savings-loan-crisis", name: "Savings & Loan Crisis", date: "1989", description: "Thrift-industry insolvencies from duration mismatch and fraud." },
];
