import { readdirSync } from "fs";
import { INDUSTRIES, COMPANIES, THEMES, CONCEPTS, EVENTS } from "./entities";

type PassageLine = {
  text: string;
  sequence: number;
  visibility: string;
  themes: string[];
  concepts: string[];
  companies: string[];
  events: string[];
};

type CorpusLine = {
  personSlug: string;
  source: {
    slug: string;
    title: string;
    year: number | null;
    sourceType: string;
    publisher: string;
    url: string;
  };
  passages: PassageLine[];
};

const PEOPLE = [
  { slug: "buffett", name: "Warren Buffett", birthYear: 1930, sortOrder: 1, shortDescription: "Chairman of Berkshire Hathaway and history's most studied capital allocator.", bio: "Warren Buffett (b. 1930) ran Buffett Partnership Ltd. from 1957 to 1969 before taking control of Berkshire Hathaway. His annual letters to shareholders, written since 1977, form one of the most complete public records of any investor's thinking." },
  { slug: "munger", name: "Charlie Munger", birthYear: 1924, sortOrder: 2, shortDescription: "Berkshire Hathaway vice chairman and architect of worldly wisdom.", bio: "Charlie Munger (1924\u20132023) was Berkshire Hathaway's vice chairman and Warren Buffett's partner for over five decades. His Wesco Financial letters and talks on psychology and decision-making shaped modern value investing." },
  { slug: "marks", name: "Howard Marks", birthYear: 1946, sortOrder: 3, shortDescription: "Oaktree co-founder whose client memos chronicle cycles and risk.", bio: "Howard Marks (b. 1946) co-founded Oaktree Capital Management, a leader in credit investing. Since 1990 his memos to clients have been required reading across the investment world." },
  { slug: "lynch", name: "Peter Lynch", birthYear: 1944, sortOrder: 4, shortDescription: "Magellan Fund manager who taught investors to know what they own.", bio: "Peter Lynch (b. 1944) managed Fidelity's Magellan Fund from 1977 to 1990, averaging roughly 29% annually. His lectures and interviews popularized investing in what you know." },
  { slug: "graham", name: "Benjamin Graham", birthYear: 1894, sortOrder: 5, shortDescription: "Father of value investing and author of Security Analysis.", bio: "Benjamin Graham (1894\u20131976) codified security analysis and the margin of safety. His Senate testimony and late-career interviews remain primary documents of disciplined investing." },
  { slug: "bogle", name: "John Bogle", birthYear: 1929, sortOrder: 6, shortDescription: "Vanguard founder and permanent champion of the index fund.", bio: "John C. Bogle (1929\u20132019) founded Vanguard and created the first retail index fund. His speeches and essays on costs, compounding, and investor behavior reshaped an industry." },
  { slug: "klarman", name: "Seth Klarman", birthYear: 1957, sortOrder: 7, shortDescription: "Baupost Group president and author of Margin of Safety.", bio: "Seth Klarman (b. 1957) founded The Baupost Group in 1982. His absolute-return, risk-first approach made Margin of Safety (1991) one of the most sought-after investing books ever printed." },
  { slug: "soros", name: "George Soros", birthYear: 1930, sortOrder: 8, shortDescription: "Macro investor and theorist of reflexivity.", bio: "George Soros (b. 1930) built Quantum Fund into one of history's greatest track records. His CEU lectures articulate reflexivity, the feedback loop between market beliefs and reality." },
  { slug: "druckenmiller", name: "Stanley Druckenmiller", birthYear: 1953, sortOrder: 9, shortDescription: "Duquesne founder; macro concentration and asymmetric bets.", bio: "Stanley Druckenmiller (b. 1953) ran Duquesne Capital for three decades without a losing year and co-drove Quantum's legendary run with Soros." },
  { slug: "simons", name: "Jim Simons", birthYear: 1938, sortOrder: 10, shortDescription: "Mathematician who built Renaissance Technologies.", bio: "Jim Simons (1938\u20132024) applied mathematics and data to found Renaissance Technologies, whose Medallion fund set records for systematic returns." },
  { slug: "livermore", name: "Jesse Livermore", birthYear: 1877, sortOrder: 11, shortDescription: "Legendary speculator of the 1907 and 1929 crashes.", bio: "Jesse Livermore (1877\u20131940) shorted both the 1907 panic and the 1929 crash. How to Trade in Stocks (1940) distilled his tape-reading discipline." },
  { slug: "dalio", name: "Ray Dalio", birthYear: 1949, sortOrder: 12, shortDescription: "Bridgewater founder; principles and economic machine frameworks.", bio: "Ray Dalio (b. 1949) founded Bridgewater Associates and codified his decision-making into Principles and his template of debt cycles." },
  { slug: "templeton", name: "John Templeton", birthYear: 1912, sortOrder: 13, shortDescription: "Global contrarian pioneer of bargain hunting worldwide.", bio: "Sir John Templeton (1912\u20132008) pioneered global contrarian investing, buying at maximum pessimism across markets few Americans watched." },
  { slug: "greenblatt", name: "Joel Greenblatt", birthYear: 1957, sortOrder: 14, shortDescription: "Gotham Capital founder; special situations and the Magic Formula.", status: "coming_later" },
  { slug: "fisher", name: "Philip Fisher", birthYear: 1907, sortOrder: 15, shortDescription: "Growth-investing pioneer and author of Common Stocks and Uncommon Profits." },
  { slug: "pabrai", name: "Mohnish Pabrai", birthYear: 1964, sortOrder: 16, shortDescription: "Dhandho value investor and devoted student of Buffett and Munger.", status: "coming_later" },
  { slug: "ackman", name: "Bill Ackman", birthYear: 1966, sortOrder: 17, shortDescription: "Pershing Square founder; activist, concentrated public positions.", status: "coming_later" },
  { slug: "icahn", name: "Carl Icahn", birthYear: 1936, sortOrder: 18, shortDescription: "The original corporate raider turned activist shareholder." },
  { slug: "swensen", name: "David Swensen", birthYear: 1954, sortOrder: 19, shortDescription: "Yale endowment architect of institutional portfolio management.", status: "coming_later" },
  { slug: "smith", name: "Terry Smith", birthYear: 1954, sortOrder: 20, shortDescription: "Fundsmith founder; buy good companies and do nothing.", status: "coming_later" },

  // ── US founders collection (founders-collection branch, 2026-08-24) ──
  // sortOrder 1-14 places the American builders first on /founders
  // (chronological by birth). kind/region get set by tag-founders.ts
  // (US_FOUNDERS). NOTE: sortOrder changes to existing rows need the
  // fixup in the ingest runbook (upsert update clause only touches status).
  { slug: "vanderbilt", name: "Cornelius Vanderbilt", birthYear: 1794, sortOrder: 1, shortDescription: "Steamship and railroad consolidator; the original American comprador of infrastructure.", bio: "Cornelius Vanderbilt (1794-1877) built fortunes first in steamships and then in railroads, consolidating the New York Central system and pioneering large-scale corporate combination decades before the trust form existed. His later years gave the founding gift to Vanderbilt University. The record is thin on his own writing — he left few letters — and dense on what contemporaries and historians documented." },
  { slug: "carnegie", name: "Andrew Carnegie", birthYear: 1835, sortOrder: 2, shortDescription: "Steel magnate who codified the Gospel of Wealth and gave away nearly his entire fortune.", bio: "Andrew Carnegie (1835-1919) built Carnegie Steel into the largest steel operation in America, sold it to J.P. Morgan in 1901 to form U.S. Steel, then systematically gave away the proceeds through libraries, universities and foundations. His 1889 essay The Gospel of Wealth remains the canonical statement of obligations attached to great fortunes." },
  { slug: "jp-morgan", name: "J.P. Morgan", birthYear: 1837, sortOrder: 3, shortDescription: "Wall Street's great reorganizer; the 1895 gold rescue and the 1907 panic response.", bio: "John Pierpont Morgan (1837-1913) built J.P. Morgan & Co. into the dominant force in American finance, reorganized railroads and the steel industry, led the 1895 rescue of the U.S. gold standard and the 1907 panic response that prefigured the Federal Reserve. His art collection became the Morgan Library." },
  { slug: "rockefeller", name: "John D. Rockefeller", birthYear: 1839, sortOrder: 4, shortDescription: "Founder of Standard Oil; the reference case for consolidation and structured philanthropy.", bio: "John D. Rockefeller (1839-1937) co-founded Standard Oil in 1870 and built it into the most complete industrial consolidation of its era, pioneering systematic cost accounting, vertical integration and the trust form. The 1911 Supreme Court breakup spawned the modern oil majors; his philanthropy created the University of Chicago and the Rockefeller Foundation." },
  { slug: "henry-ford", name: "Henry Ford", birthYear: 1863, sortOrder: 5, shortDescription: "Moving assembly line, the $5 day, and the Model T that motorized America.", bio: "Henry Ford (1863-1947) founded Ford Motor Company in 1903 and industrialized the automobile with the moving assembly line, the single-model Model T strategy and the 1914 $5 workday. My Life and Work (1922) set out his philosophy of mass production and service; his later antisemitic campaigns remain a permanent stain on the record." },
  { slug: "walt-disney", name: "Walt Disney", birthYear: 1901, sortOrder: 6, shortDescription: "Animator and studio builder; Mickey Mouse, Snow White, Disneyland and the Walt Disney Company.", bio: "Walt Disney (1901-1966) founded the Disney Brothers studio in 1923, bet the studio on Snow White and the Seven Dwarfs (1937) — the first feature-length animated film — and extended the enterprise into Disneyland (1955) and the Walt Disney World project completed after his death. A continuous public record of interviews, broadcasts and public statements documents the operating philosophy." },
  { slug: "sam-walton", name: "Sam Walton", birthYear: 1918, sortOrder: 7, shortDescription: "Founder of Walmart; everyday low prices, distribution discipline and rural retail.", bio: "Sam Walton (1918-1992) opened the first Wal-Mart in Rogers, Arkansas in 1962 and built the largest retailer in the world on everyday low prices, saturation distribution in small towns, and a relentless cost culture. Made in America (1992), his autobiography written with John Huey, remains the canonical operator's account of the business." },
  { slug: "howard-schultz", name: "Howard Schultz", birthYear: 1953, sortOrder: 8, shortDescription: "Starbucks CEO and chairman; the third-place coffee experience and the benefits precedent.", bio: "Howard Schultz (b. 1953) joined Starbucks in 1982, bought the company in 1987 and scaled it from a Seattle roaster into a global third-place coffee brand, pioneering health benefits and stock options for part-time workers along the way. Pour Your Heart Into It (1997) and Onward (2011) document the operating decisions." },
  { slug: "steve-jobs", name: "Steve Jobs", birthYear: 1955, sortOrder: 9, shortDescription: "Co-founder of Apple; the Macintosh, NeXT, Pixar, and the second-act consumer revolution.", bio: "Steve Jobs (1955-2011) co-founded Apple in 1976, launched the Macintosh in 1984, was ousted the next year, built NeXT and turned Pixar into the era's defining animation studio, then returned in 1997 to lead the iPod-iPhone-iPad run that made Apple the most valuable company in the world. Product philosophy in the 2005 Stanford commencement address and decades of public keynotes." },
  { slug: "bill-gates", name: "Bill Gates", birthYear: 1955, sortOrder: 10, shortDescription: "Co-founder of Microsoft; the PC software platform and systematic global philanthropy.", bio: "Bill Gates (b. 1955) co-founded Microsoft in 1975 and built the software platform of the personal-computer era, from BASIC and DOS to Windows and Office. Since 2008 he has run the Gates Foundation, applying measured-outcome methods to global health and development. His books and annual letters form a continuous public record." },
  { slug: "reed-hastings", name: "Reed Hastings", birthYear: 1960, sortOrder: 11, shortDescription: "Co-founder and CEO of Netflix; the DVD-to-streaming pivot and the culture deck.", bio: "Reed Hastings (b. 1960) co-founded Netflix in 1997 as a DVD-by-mail service, took it public in 2002, and drove the pivot to streaming and original content that made it the reference case for platform transition. The Netflix Culture Deck (2009) and No Rules Rules (2020) codify the management philosophy; his Pure Software exit documents the first act." },
  { slug: "bezos", name: "Jeff Bezos", birthYear: 1964, sortOrder: 12, shortDescription: "Founder of Amazon; the everything store, AWS, and the Day 1 operating doctrine.", bio: "Jeff Bezos (b. 1964) founded Amazon in 1994 and built it from an online bookstore into the everything store and, through AWS, the backbone of cloud computing. His annual shareholder letters (1997-2020) codify long-term thinking, customer obsession and the Day 1 doctrine; he later founded Blue Origin and owns The Washington Post." },
  { slug: "elon-musk", name: "Elon Musk", birthYear: 1971, sortOrder: 13, shortDescription: "Co-founder of PayPal; CEO of Tesla and SpaceX; first-principles hardware bets.", bio: "Elon Musk (b. 1971) co-founded Zip2 and X.com (which merged into PayPal), then led Tesla's electric-vehicle turnaround and founded SpaceX, whose reusable Falcon 9 rewrote launch economics. Acquired Twitter/X in 2022. His interviews, product presentations and company communications document a first-principles, vertically-integrated approach to hardware risk." },
  { slug: "zuckerberg", name: "Mark Zuckerberg", birthYear: 1984, sortOrder: 14, shortDescription: "Co-founder and CEO of Meta (Facebook); the social graph, mobile pivot, and the metaverse bet.", bio: "Mark Zuckerberg (b. 1984) founded Facebook from Harvard in 2004 and scaled it into the largest social network in the world, driving the 2012 pivot to mobile and the 2021 rebrand to Meta around the metaverse bet. A continuous public record — interviews, letters, and congressional testimony — documents the growth and governance decisions." },
  { slug: "jamsetji-tata", name: "Jamsetji Tata", birthYear: 1869, sortOrder: 101, shortDescription: "Founding patriarch of the Tata Group; conceived steel, hydroelectric power and a research university.", bio: "Founder of the Tata Group (1839-1904). Began with Empress Mills in Nagpur in 1877; conceived Tata Steel, Tata Power and the Indian Institute of Science, completed by successors after his death. The trust-ownership structure that routes Tata Sons dividends to philanthropy traces to his bequest." },
  { slug: "jrd-tata", name: "JRD Tata", birthYear: 1904, sortOrder: 102, shortDescription: "Chairman of Tata Sons 1938-1988; founder of Indian civil aviation.", bio: "Jehangir Ratanji Dadabhoy Tata (1904-1993) led Tata Sons for half a century, grew the group to nearly a hundred companies, founded Tata Airlines (later Air India) in 1932, and introduced employee welfare provisions decades before they became statutory." },
  { slug: "ratan-tata", name: "Ratan Tata", birthYear: 1937, sortOrder: 103, shortDescription: "Chairman of Tata Sons 1991-2012; drove the global M&A wave (Tetley, Corus, JLR) and the Nano bet.", bio: "Ratan Naval Tata (b. 1937) succeeded JRD Tata in 1991 and globalised the group through overseas acquisitions. Returned as interim chairman during the 2016 Mistry affair. Chairman Emeritus of Tata Sons." },
  { slug: "gd-birla", name: "Ghanshyam Das Birla", birthYear: 1894, sortOrder: 104, shortDescription: "Founder of the Birla Group; diversified from jute into aluminium, cement and chemicals.", bio: "Ghanshyam Das Birla (1894-1983) built the Birla Group from a Bengal jute-trading base into textiles, aluminium (Hindalco), cement and viscose. A close associate and funder of Mahatma Gandhi; founded Birla Engineering College, Pilani (BITS)." },
  { slug: "dhirubhai-ambani", name: "Dhirubhai Ambani", birthYear: 1932, sortOrder: 105, shortDescription: "Founder of Reliance Industries; pioneered the Indian equity cult.", bio: "Dhirajlal Hirachand Ambani (1932-2002) founded Reliance in 1966 as a textile trader and built it into India's largest private-sector company via integrated petrochemicals and refining (Hazira, Jamnagar). Credited with seeding the Indian retail-equity cult." },
  { slug: "karsanbhai-patel", name: "Karsanbhai Patel", birthYear: 1945, sortOrder: 106, shortDescription: "Founder of Nirma; the Indian bottom-of-the-pyramid consumer reference case.", bio: "Karsanbhai Patel (b. 1945) founded Nirma from an Ahmedabad garage in 1969 with a low-priced detergent that undercut the incumbents and built a national consumer-goods business on pricing, distribution and backward integration, without ceding promoter equity for decades." },
  { slug: "jamnalal-bajaj", name: "Jamnalal Bajaj", birthYear: 1889, sortOrder: 107, shortDescription: "Founder of the Bajaj Group; Gandhian industrialist and treasurer of the independence movement.", bio: "Jamnalal Bajaj (1889-1942) founded the Bajaj Group and was a close associate and funder of Mahatma Gandhi. His sons Kamalnayan and Ramkrishna carried the group into Bajaj Auto and Bajaj Electricals after independence." },
  { slug: "rahul-bajaj", name: "Rahul Bajaj", birthYear: 1938, sortOrder: 108, shortDescription: "Scaled Bajaj Auto through the licence-raj and post-liberalisation decades.", bio: "Rahul Bajaj (1938-2022) led Bajaj Auto through India's licence era as the dominant two-wheeler incumbent and through the post-1991 transition when the protected market opened to Japanese joint-venture entrants. Chairman emeritus of the Bajaj Group." },
  { slug: "ardeshir-godrej", name: "Ardeshir Godrej", birthYear: 1868, sortOrder: 109, shortDescription: "Founder of the Godrej Group around the springless lock (1897).", bio: "Ardeshir Burjorji Sorabji Godrej (1868-1936) founded the Godrej Group in 1897 with a hand-cast springless lock and extended it into soaps, safes and steel furniture, establishing the diversification logic and trust-ownership posture the group retains." },
  { slug: "verghese-kurien", name: "Verghese Kurien", birthYear: 1921, sortOrder: 110, shortDescription: "Architect of India's White Revolution and the Amul cooperative model.", bio: "Verghese Kurien (1921-2012) engineered the White Revolution, building the Anand cooperative (Amul/GCMMF) and NDDB into a producer-owned dairy structure that made India the world's largest milk producer through institutional rather than technological innovation." },
  { slug: "walchand-hirachand", name: "Walchand Hirachand", birthYear: 1882, sortOrder: 111, shortDescription: "Pioneer of Indian-owned shipping, aviation and automobile manufacturing.", bio: "Walchand Hirachand (1882-1953) founded Scindia Steam Navigation (1919), Hindustan Aircraft (1940) and Premier Automobiles (1944), entering sectors the colonial state had treated as European preserves." },
  { slug: "brijmohan-lall-munjal", name: "Brijmohan Lall Munjal", birthYear: 1924, sortOrder: 112, shortDescription: "Founder of Hero Cycles and the Hero Honda joint venture.", bio: "Brijmohan Lall Munjal (1924-2015) founded Hero Cycles in 1956 (the world's largest bicycle maker) and the 1984 Honda joint venture Hero Honda, which became the world's largest two-wheeler manufacturer. The JV was amicably terminated in 2011." },
  { slug: "kk-birla", name: "K.K. Birla", birthYear: 1915, sortOrder: 113, shortDescription: "Steward of a Birla branch weighted toward media (Hindustan Times), fertilisers and viscose.", bio: "Krishna Kumar Birla (1915-2008) carried forward a segment of the Birla family interests spanning sugar, fertilisers, textiles, viscose (Century, Zuari) and the Hindustan Times, distinguishing his branch through an explicit media-and-chemicals weighting." },
  { slug: "ramkrishna-bajaj", name: "Ramkrishna Bajaj", birthYear: 1923, sortOrder: 114, shortDescription: "Steward of the Bajaj Group through the licence-raj decades.", bio: "Ramkrishna Bajaj (1923-1994) was the younger son of Jamnalal Bajaj and chaired the Bajaj Group through the licence-raj period in which Bajaj Auto became the dominant Indian two-wheeler maker. Established the Jamnalal Bajaj Foundation and its awards." },
  { slug: "mukesh-ambani", name: "Mukesh Ambani", birthYear: 1957, sortOrder: 201, shortDescription: "Chairman of Reliance Industries; the Jio price-war and the retail and digital pivots.", bio: "Mukesh Ambani (b. 1957) chairs Reliance Industries and led the group's expansion from petrochemicals and refining into telecom (Reliance Jio, launched 2016) and retail, redefining the group's consumer-facing footprint." },
  { slug: "anil-agarwal", name: "Anil Agarwal", birthYear: 1954, sortOrder: 202, shortDescription: "Founder and chairman of Vedanta; the mining and metals bet.", bio: "Anil Agarwal (b. 1954) founded Sterlite Industries and built Vedanta Resources into a diversified mining and metals house, listing the holding company in London in 2003 before re-domiciling to India." },
  { slug: "gautam-adani", name: "Gautam Adani", birthYear: 1962, sortOrder: 203, shortDescription: "Founder of the Adani Group; ports-to-energy conglomerate and the Hindenburg episode.", bio: "Gautam Adani (b. 1962) founded the Adani Group and built it from ports into energy, logistics and green energy. The January 2023 Hindenburg report and its aftermath are the defining public test of the group's leverage and disclosure posture." },
  { slug: "kumar-mangalam-birla", name: "Kumar Mangalam Birla", birthYear: 1967, sortOrder: 204, shortDescription: "Chairman of the Aditya Birla Group; modernisation and the Vodafone Idea gamble.", bio: "Kumar Mangalam Birla (b. 1967) chairs the Aditya Birla Group and led its globalisation (Novellis, Columbian Chemicals) and its telecom exposure through Idea Cellular and the Vodafone Idea merger." },
  { slug: "anand-mahindra", name: "Anand Mahindra", birthYear: 1955, sortOrder: 205, shortDescription: "Chairman of the Mahindra Group; farm-to-auto-to-tech pivot.", bio: "Anand Mahindra (b. 1955) chairs the Mahindra Group and led its diversification into IT services (the Tech Mahindra/Satyam merger), financial services and electric vehicles, alongside a high-profile public communications posture." },
  { slug: "sunil-bharti-mittal", name: "Sunil Bharti Mittal", birthYear: 1957, sortOrder: 206, shortDescription: "Founder of Bharti Enterprises; the telecom outsourcing model and the Zain Africa acquisition.", bio: "Sunil Bharti Mittal (b. 1957) built Bharti Airtel into one of India's largest telecom operators through the network and IT outsourcing model, and extended the model across Africa via the 2010 Zain acquisition." },
  { slug: "naveen-jindal", name: "Naveen Jindal", birthYear: 1970, sortOrder: 207, shortDescription: "Chairman of Jindal Steel and Power; the flag-rights case and the coal-allocation episode.", bio: "Naveen Jindal (b. 1970) leads Jindal Steel and Power and is a former two-term member of Parliament, known for the Supreme Court case that secured the citizen's right to fly the national flag and for the 2014 coal-block de-allocation that reshaped JSPL's raw-material base." },
  { slug: "op-jindal", name: "O.P. Jindal", birthYear: 1930, sortOrder: 208, shortDescription: "Founder of the Jindal Group; the pipe-to-steel-and-power vertical integration.", bio: "Om Prakash Jindal (1930-2005) founded the Jindal Group from a pipe-manufacturing unit in 1952 and built it into a vertically integrated steel-and-power house, with the operating businesses later split among his sons." },
  { slug: "narayana-murthy", name: "N.R. Narayana Murthy", birthYear: 1946, sortOrder: 301, shortDescription: "Co-founder of Infosys; the $250 founding and the Indian IT services model.", bio: "Nagavara Ramarao Narayana Murthy (b. 1946) co-founded Infosys in 1981 with $250 borrowed from his wife and built it into a global IT-services firm, anchoring the Indian offshore services model and the equity-governance posture associated with it." },
  { slug: "nandan-nilekani", name: "Nandan Nilekani", birthYear: 1955, sortOrder: 302, shortDescription: "Co-founder of Infosys and architect of Aadhaar as public infrastructure.", bio: "Nandan Nilekani (b. 1955) co-founded Infosys and led the UIDAI/Aadhaar programme, treating identity as public infrastructure. Returned as Infosys chairman in 2017." },
  { slug: "azim-premji", name: "Azim Premji", birthYear: 1945, sortOrder: 303, shortDescription: "Chairman of Wipro; the pivot from vegetable oil to IT services and the philanthropic endowment.", bio: "Azim Premji (b. 1945) chairs Wipro and led its pivot from a vegetable-oil trading company into a global IT-services firm. His philanthropic endowment, routed through the Azim Premji Foundation, is among the largest by an Indian promoter." },
  { slug: "shiv-nadar", name: "Shiv Nadar", birthYear: 1945, sortOrder: 304, shortDescription: "Founder of HCL; the hardware-to-services transition and the Shiv Nadar Foundation.", bio: "Shiv Nadar (b. 1945) founded HCL in 1976 as a hardware venture and led its transition into IT services (HCL Technologies), building one of the largest Indian offshore services firms alongside Infosys and Wipro." },
  { slug: "fc-kohli", name: "F.C. Kohli", birthYear: 1924, sortOrder: 305, shortDescription: "Father of the Indian IT services industry; first CEO of TCS.", bio: "Faqir Chand Kohli (1924-2020) was the first chief executive of Tata Consultancy Services and is credited with establishing the Indian IT-services industry's operating model from the 1960s onward." },
  { slug: "ramalinga-raju", name: "Byrraju Ramalinga Raju", birthYear: 1954, sortOrder: 306, shortDescription: "Founder of Satyam; the 2009 confession and the governance-failure reference case.", bio: "Byrraju Ramalinga Raju (b. 1954) founded Satyam Computer Services in 1987 and built it into India's fourth-largest IT services firm before his January 2009 confession to having falsified the firm's accounts over several years, the defining corporate-governance failure of Indian tech's first wave." },
  { slug: "kishore-biyani", name: "Kishore Biyani", birthYear: 1971, sortOrder: 401, shortDescription: "Founder of Future Group; the rise and the Future-Reliance retail collapse.", bio: "Kishore Biyani (b. 1971) founded the Future Group and built Big Bazaar into India's largest modern retail footprint before the group's 2020-22 insolvency and the contested Future-Reliance retail transaction." },
  { slug: "kiran-mazumdar-shaw", name: "Kiran Mazumdar-Shaw", birthYear: 1953, sortOrder: 402, shortDescription: "Founder of Biocon; biotech from a Bangalore garage.", bio: "Kiran Mazumdar-Shaw (b. 1953) founded Biocon in 1978 from a Bangalore garage and built it into India's leading biotechnology firm, with a research pipeline in insulin analogues and oncology." },
  { slug: "yc-deveshwar", name: "Y.C. Deveshwar", birthYear: 1947, sortOrder: 403, shortDescription: "Chairman of ITC; the diversification defense strategy.", bio: "Yogesh Chander Deveshwar (1947-2019) chaired ITC from 1996 and led its diversification from cigarettes into FMCG, hotels, paperboards and agribusiness, framing the strategy as a defense of the cigarette cash-cow through adjacent category build-outs." },
  { slug: "ramesh-chauhan", name: "Ramesh Chauhan", birthYear: 1944, sortOrder: 404, shortDescription: "Founder of Parle and Bisleri; the Thums Up sale to Coca-Cola.", bio: "Ramesh Chauhan (b. 1944) built Parle's Thums Up, Limca and Gold Spot into the dominant Indian soft-drink brands, sold them to Coca-Cola in 1993, and later built Bisleri into the packaged-water category leader." },
  { slug: "cyrus-poonawalla", name: "Cyrus Poonawalla", birthYear: 1941, sortOrder: 405, shortDescription: "Founder of the Serum Institute; the vaccine scale bet.", bio: "Cyrus Poonawalla (b. 1941) founded the Serum Institute of India in 1966 and built it into the world's largest vaccine manufacturer by dose volume, the basis of India's role in global immunisation." },
  { slug: "sachin-and-binny-bansal", name: "Sachin Bansal & Binny Bansal", birthYear: 1981, sortOrder: 501, shortDescription: "Co-founders of Flipkart; the build-and-sell-to-Walmart arc.", bio: "Sachin Bansal (b. 1981) and Binny Bansal (b. 1983) co-founded Flipkart in 2007 and built it into India's leading e-commerce firm, sold to Walmart in 2018 for ~$16 billion. Both departed the firm subsequently." },
  { slug: "deepinder-goyal", name: "Deepinder Goyal", birthYear: 1983, sortOrder: 502, shortDescription: "Founder of Zomato (Eternal); survival through multiple pivots.", bio: "Deepinder Goyal (b. 1983) founded Zomato (later Eternal) in 2008 and led it through the food-listing, food-delivery and quick-commerce (Blinkit) pivots to a 2021 listing and a broader hyperlocal-commerce posture." },
  { slug: "bhavish-and-ankit-ola", name: "Bhavish Aggarwal & Ankit Bhati", birthYear: 1985, sortOrder: 503, shortDescription: "Co-founders of Ola; the ride-hailing to EV pivot.", bio: "Bhavish Aggarwal (b. 1985) and Ankit Bhati (b. 1985) co-founded Ola in 2010 and built it into India's leading ride-hailing platform; Bhavish subsequently led the Ola Electric EV pivot." },
  { slug: "vijay-shekhar-sharma", name: "Vijay Shekhar Sharma", birthYear: 1978, sortOrder: 504, shortDescription: "Founder of Paytm; the RBI payments-bank clampdown as an Outcome case.", bio: "Vijay Shekhar Sharma (b. 1978) founded One97 Communications and built Paytm into India's largest payments brand, a trajectory sharply tested by the Reserve Bank of India's 2022-24 restrictions on Paytm Payments Bank." },
  { slug: "falguni-nayar", name: "Falguni Nayar", birthYear: 1963, sortOrder: 505, shortDescription: "Founder of Nykaa; the inventory-led beauty e-commerce and the profitable listing.", bio: "Falguni Nayar (b. 1963) founded Nykaa in 2012 after a career in investment banking and listed it in 2021 as one of the rare Indian consumer-tech unicorns to be operating-profitable at listing." },
  { slug: "ritesh-agarwal", name: "Ritesh Aggarwal", birthYear: 1994, sortOrder: 506, shortDescription: "Founder of OYO; aggressive scaling then contraction.", bio: "Ritesh Aggarwal (b. 1994) founded OYO Rooms in 2013, scaled it into a global hospitality-tech firm and led the pandemic-era contraction that re-priced the model ahead of a planned IPO." },
  { slug: "byju-raveendran", name: "Byju Raveendran", birthYear: 1980, sortOrder: 507, shortDescription: "Founder of BYJU'S; the insolvency and contempt proceedings (developing).", bio: "Byju Raveendran (b. 1980) built Think and Learn / BYJU'S into India's most valued startup and a global edtech benchmark before its 2022-24 valuation collapse, insolvency proceedings and the founder's personal legal exposure, which remains developing." },
  { slug: "nithin-and-nikhil-kamath", name: "Nithin Kamath & Nikhil Kamath", birthYear: 1986, sortOrder: 508, shortDescription: "Co-founders of Zerodha; profitable-by-design bootstrapping.", bio: "Nithin Kamath (b. 1986) and Nikhil Kamath (b. 1986) co-founded Zerodha in 2010 and built it into India's largest retail brokerage by active clients on a bootstrapped, profitable-by-design model against VC-funded rivals." },
  { slug: "girish-mathrubootham", name: "Girish Mathrubootham", birthYear: 1975, sortOrder: 509, shortDescription: "Founder of Freshworks; the first Indian SaaS Nasdaq listing.", bio: "Girish Mathrubootham (b. 1975) founded Freshworks (Freshdesk) in 2010 and listed it on Nasdaq in 2021, the first Indian-origin SaaS company to do so, building the template for the wider Indian SaaS wave." },
  { slug: "kunal-and-rohit-snapdeal", name: "Kunal Bahl & Rohit Bansal", birthYear: 1982, sortOrder: 510, shortDescription: "Co-founders of Snapdeal; the rise and the retreat.", bio: "Kunal Bahl (b. 1982) and Rohit Bansal (b. 1982) co-founded Snapdeal in 2010, scaled it into a leading horizontal marketplace and led the post-2017 retreat from the horizontal model to a focused value-commerce platform after the failed Flipkart merger." },
  { slug: "sriharsha-and-nandan-swiggy", name: "Sriharsha Majety & Nandan Reddy", birthYear: 1984, sortOrder: 511, shortDescription: "Co-founders of Swiggy; food delivery and the Instamart pivot.", bio: "Sriharsha Majety and Nandan Reddy co-founded Swiggy in 2014 and built it into India's leading food-delivery platform, extending into quick commerce (Instamart) and a 2024 listing." },
  { slug: "ashneer-grover", name: "Ashneer Grover", birthYear: 1982, sortOrder: 512, shortDescription: "Co-founder of BharatPe; the public ouster as a governance case.", bio: "Ashneer Grover (b. 1982) co-founded BharatPe in 2018 and was ousted in 2022 after an external governance review of his conduct and related-party transactions, the standard Indian case of founder-led fintech governance failure." },
  { slug: "divyank-turakhia", name: "Divyank Turakhia", birthYear: 1982, sortOrder: 513, shortDescription: "Founder of Media.net; the quiet $900M ad-tech exit.", bio: "Divyank Turakhia (b. 1982) co-founded Media.net and sold the contextual-advertising business to a Chinese consortium in 2016 for ~$900 million, an exit notable for its size and for the founder's deliberate avoidance of public-promoter visibility." },
  { slug: "varun-alagh", name: "Varun Alagh", birthYear: 1985, sortOrder: 601, shortDescription: "Co-founder of Mamaearth/Honasa; the D2C-to-IPO arc.", bio: "Varun Alagh (b. 1985) co-founded Mamaearth in 2016 and built it into India's largest D2C personal-care brand, listing Honasa Consumer in 2023 amid a public debate on the IPO's pricing." },
  { slug: "ghazal-alagh", name: "Ghazal Alagh", birthYear: 1985, sortOrder: 602, shortDescription: "Co-founder of Mamaearth/Honasa.", bio: "Ghazal Alagh (b. 1985) co-founded Mamaearth alongside Varun Alagh and led the brand's product and content posture through the D2C-to-IPO arc." },
  { slug: "suchi-mukherjee", name: "Suchi Mukherjee", birthYear: 1972, sortOrder: 603, shortDescription: "Founder of LimeRoad; the social-commerce wind-down.", bio: "Suchi Mukherjee founded LimeRoad in 2012 as a women-focused social-commerce platform and led the venture until its 2018 acquisition by V-Mart after a wind-down of the standalone model." },
  { slug: "sameer-nigam", name: "Sameer Nigam", birthYear: 1978, sortOrder: 604, shortDescription: "Founder of PhonePe; UPI dominance and the India domicile move.", bio: "Sameer Nigam (b. 1978) co-founded PhonePe inside Flipkart in 2015, built it into India's dominant UPI payments platform by transaction share, and led the 2022 spin-out and India domicile shift." },
  { slug: "harsh-and-bhavit-dream11", name: "Harsh Jain & Bhavit Sheth", birthYear: 1986, sortOrder: 605, shortDescription: "Co-founders of Dream11; the fantasy-sports regulatory tightrope.", bio: "Harsh Jain (b. 1986) and Bhavit Sheth co-founded Dream11 in 2008 and built it into India's dominant fantasy-sports platform, defending the game-of-skill format across multiple state jurisdictions." },
  { slug: "cao-dewang", name: "Cao Dewang", birthYear: 1946, sortOrder: 21, shortDescription: "Fujianese entrepreneur, born to a family that lost its wealth fleeing the Chinese civil war, who left school at 14 amid poverty and went on to build Fuyao Group into one of the world's largest automot", bio: "Fujianese entrepreneur, born to a family that lost its wealth fleeing the Chinese civil war, who left school at 14 amid poverty and went on to build Fuyao Group into one of the world's largest automotive glass manufacturers." },
  { slug: "chen-tianqiao", name: "Chen Tianqiao", birthYear: 1973, sortOrder: 22, shortDescription: "Fudan University economics graduate who founded online gaming company Shanda in 1999 with family members, grew it into China's largest internet company by market capitalization by 2004, took it privat", bio: "Fudan University economics graduate who founded online gaming company Shanda in 1999 with family members, grew it into China's largest internet company by market capitalization by 2004, took it private in 2012, and now runs Shanda Group as a family investment firm while funding brain-science research through the Tianqiao and Chrissy Chen Institute." },
  { slug: "chen-yidan", name: "Chen Yidan", birthYear: 1971, sortOrder: 23, shortDescription: "Co-founded Tencent in 1998 alongside Ma Huateng, Zhang Zhidong, Xu Chenye, and Zeng Liqing, serving as Chief Administrative Officer and later leading Tencent's philanthropic arm, then stepped down as ", bio: "Co-founded Tencent in 1998 alongside Ma Huateng, Zhang Zhidong, Xu Chenye, and Zeng Liqing, serving as Chief Administrative Officer and later leading Tencent's philanthropic arm, then stepped down as CAO in March 2013 to focus on philanthropy, founding the Chen Yidan Charity Foundation, co-founding Wuhan College in 2009, and establishing the HK$2.5 billion (US$320 million) Yidan Prize in 2016 to recognize education innovators worldwide." },
  { slug: "cheng-wei", name: "Cheng Wei (Will Cheng)", birthYear: null, sortOrder: 24, shortDescription: "Founded ride-hailing app Didi Dache in 2012, grew it via a 2015 merger with rival Kuaidi Dache and the 2016 acquisition of Uber's China operations, then led the company through a 2021 NYSE IPO, a subs", bio: "Founded ride-hailing app Didi Dache in 2012, grew it via a 2015 merger with rival Kuaidi Dache and the 2016 acquisition of Uber's China operations, then led the company through a 2021 NYSE IPO, a subsequent year-long Chinese cybersecurity probe, a $1.2 billion fine, and a 2022 NYSE delisting." },
  { slug: "colin-huang", name: "Colin Huang (Huang Zheng)", birthYear: 1980, sortOrder: 25, shortDescription: "Former Google engineer who founded social e-commerce platform Pinduoduo in 2015, grew it into China's second-largest e-commerce platform by market capitalization, and stepped down as CEO in 2020 to fo", bio: "Former Google engineer who founded social e-commerce platform Pinduoduo in 2015, grew it into China's second-largest e-commerce platform by market capitalization, and stepped down as CEO in 2020 to focus on long-term strategy as chairman." },
  { slug: "ding-lei", name: "Ding Lei (William Ding)", birthYear: null, sortOrder: 26, shortDescription: "Founder of NetEase, China's second-largest video gaming company at the time of a 2022 SCMP report, who stepped back from a front-line corporate role at a NetEase gaming affiliate amid tightened Chines", bio: "Founder of NetEase, China's second-largest video gaming company at the time of a 2022 SCMP report, who stepped back from a front-line corporate role at a NetEase gaming affiliate amid tightened Chinese regulatory scrutiny of the gaming sector." },
  { slug: "dong-mingzhu", name: "Dong Mingzhu", birthYear: 1954, sortOrder: 27, shortDescription: "Widowed at 36, she left her young son with his grandmother, moved to Guangdong, and joined Gree's predecessor company as an air-conditioner saleswoman in 1990, rising to president by 2001 and chairwom", bio: "Widowed at 36, she left her young son with his grandmother, moved to Guangdong, and joined Gree's predecessor company as an air-conditioner saleswoman in 1990, rising to president by 2001 and chairwoman by 2012, building Gree from an air-conditioner maker into a conglomerate spanning smart equipment, industrial robots, and new energy." },
  { slug: "guo-guangchang", name: "Guo Guangchang", birthYear: 1967, sortOrder: 28, shortDescription: "Fudan University-educated founder who started a market-research firm in 1992, then built Fosun Group from 1994 into one of China's largest privately owned conglomerates spanning insurance, pharmaceuti", bio: "Fudan University-educated founder who started a market-research firm in 1992, then built Fosun Group from 1994 into one of China's largest privately owned conglomerates spanning insurance, pharmaceuticals, property, steel, mining, retail, and asset management, briefly detained by Chinese police in December 2015 while 'assisting authorities with an investigation' before being released four days later, and stepped down from a subsidiary chairmanship in 2017 to give younger executives a bigger role while remaining chairman of the parent company." },
  { slug: "he-xiaopeng", name: "He Xiaopeng", birthYear: null, sortOrder: 29, shortDescription: "Alibaba-linked entrepreneur (sold his prior company UCWeb to Alibaba) who leads electric-vehicle maker Xpeng as chairman and CEO, personally took over Xpeng's robotics division in June 2026 ahead of m", bio: "Alibaba-linked entrepreneur (sold his prior company UCWeb to Alibaba) who leads electric-vehicle maker Xpeng as chairman and CEO, personally took over Xpeng's robotics division in June 2026 ahead of mass production of its humanoid robot 'Iron,' and joined Ant Group's board that same month." },
  { slug: "jack-ma", name: "Jack Ma", birthYear: 1964, sortOrder: 30, shortDescription: "Alibaba co-founder whose Ant Group affiliate was preparing what would have been the world's largest IPO (targeting roughly $34.5 billion) in Shanghai and Hong Kong in November 2020, when Chinese excha", bio: "Alibaba co-founder whose Ant Group affiliate was preparing what would have been the world's largest IPO (targeting roughly $34.5 billion) in Shanghai and Hong Kong in November 2020, when Chinese exchanges suspended the listing days after Ma publicly criticized financial regulators." },
  { slug: "kai-fu-lee", name: "Kai-Fu Lee", birthYear: 1961, sortOrder: 31, shortDescription: "Taiwanese-American computer scientist who led Microsoft Research China/Asia (1998-2000) and Google China (2005-2009), founded venture capital firm Innovation Works (later Sinovation Ventures) in 2009,", bio: "Taiwanese-American computer scientist who led Microsoft Research China/Asia (1998-2000) and Google China (2005-2009), founded venture capital firm Innovation Works (later Sinovation Ventures) in 2009, and founded AI company 01.AI in 2023, which builds agentic AI tools for companies using customized open-source models." },
  { slug: "lai-meisong", name: "Lai Meisong", birthYear: null, sortOrder: 32, shortDescription: "Founded ZTO Express and has served as chairman since May 2013 and CEO since the company's inception, building it into one of China's largest express-delivery companies; a former deputy chairman of the", bio: "Founded ZTO Express and has served as chairman since May 2013 and CEO since the company's inception, building it into one of China's largest express-delivery companies; a former deputy chairman of the China Express Delivery Association." },
  { slug: "lei-jun", name: "Lei Jun", birthYear: 1969, sortOrder: 33, shortDescription: "Wuhan University computer-science graduate who joined Kingsoft as an engineer in 1992, later became its CEO, founded Xiaomi, and has since transformed it into a technology conglomerate spanning smartp", bio: "Wuhan University computer-science graduate who joined Kingsoft as an engineer in 1992, later became its CEO, founded Xiaomi, and has since transformed it into a technology conglomerate spanning smartphones, electric vehicles, and chips." },
  { slug: "li-xiang", name: "Li Xiang", birthYear: null, sortOrder: 34, shortDescription: "Founded electric-vehicle maker Li Auto and continues to lead it as chairman and CEO, publicly emphasizing healthy gross margins as a core strategic goal amid intense competition in China's EV market a", bio: "Founded electric-vehicle maker Li Auto and continues to lead it as chairman and CEO, publicly emphasizing healthy gross margins as a core strategic goal amid intense competition in China's EV market as of mid-2026." },
  { slug: "li-xiting", name: "Li Xiting", birthYear: 1951, sortOrder: 35, shortDescription: "University of Science and Technology of China physics graduate who worked as a researcher in Wuhan and France before co-founding medical-device maker Mindray in Shenzhen in 1991 with Xu Hang and Cheng", bio: "University of Science and Technology of China physics graduate who worked as a researcher in Wuhan and France before co-founding medical-device maker Mindray in Shenzhen in 1991 with Xu Hang and Cheng Minghe, growing it into China's largest medical equipment manufacturer, listing it on the NYSE in 2006, taking it private in a 2016 buyout, and relisting it on China's A-share market; he became a naturalized Singaporean citizen in 2018." },
  { slug: "liang-wenfeng", name: "Liang Wenfeng", birthYear: 1985, sortOrder: 36, shortDescription: "Zhejiang University-trained engineer who co-founded quantitative hedge fund High-Flyer, built large-scale computing infrastructure that later supported AI research, and founded AI company DeepSeek in ", bio: "Zhejiang University-trained engineer who co-founded quantitative hedge fund High-Flyer, built large-scale computing infrastructure that later supported AI research, and founded AI company DeepSeek in July 2023, which gained international attention with the January 2025 release of DeepSeek-R1." },
  { slug: "liu-chuanzhi", name: "Liu Chuanzhi", birthYear: 1944, sortOrder: 37, shortDescription: "Institute of Computing Technology researcher who in 1984 used a 200,000-yuan state-institute investment to found what became Legend/Lenovo, later engineering Lenovo's 2004 acquisition of IBM's PC busi", bio: "Institute of Computing Technology researcher who in 1984 used a 200,000-yuan state-institute investment to found what became Legend/Lenovo, later engineering Lenovo's 2004 acquisition of IBM's PC business before retiring from Legend Holdings' chairmanship in December 2019." },
  { slug: "liu-hongsheng", name: "Liu Hongsheng", birthYear: 1888, sortOrder: 38, shortDescription: "Shanghai industrialist known as the \"Match King\" who built a diversified empire spanning matches, cement, coal, and wool textiles from the 1920s-1940s, and was later designated a protected \"nati...", bio: "Shanghai industrialist known as the \"Match King\" who built a diversified empire spanning matches, cement, coal, and wool textiles from the 1920s-1940s, and was later designated a protected \"nationalist capitalist\" by the Chinese Communist Party after 1949." },
  { slug: "liu-yonghao", name: "Liu Yonghao", birthYear: 1952, sortOrder: 39, shortDescription: "Former technical-school teacher who, with three brothers, quit government jobs in 1982 to raise quails and chickens, later founding the animal-feed business that became New Hope Group -- now China's l", bio: "Former technical-school teacher who, with three brothers, quit government jobs in 1982 to raise quails and chickens, later founding the animal-feed business that became New Hope Group -- now China's largest animal-feed producer -- and co-founding China Minsheng Bank." },
  { slug: "liu-yongxing", name: "Liu Yongxing", birthYear: 1948, sortOrder: 40, shortDescription: "One of four siblings from a family stigmatized as wealthy landlords before the Cultural Revolution, he and his three brothers built a quail-and-chicken-hatching business in 1982 into the Hope Group, w", bio: "One of four siblings from a family stigmatized as wealthy landlords before the Cultural Revolution, he and his three brothers built a quail-and-chicken-hatching business in 1982 into the Hope Group, which split into four sibling-led companies in 1995, with Liu Yongxing retaining and building East Hope Group into a major player in agribusiness, chemicals, and non-ferrous metals." },
  { slug: "lu-guanqiu", name: "Lu Guanqiu", birthYear: 1945, sortOrder: 41, shortDescription: "Peasant-born former ironsmith who co-founded a small agricultural-machinery factory with six other farmers in 1969 and built it into Wanxiang Group, a major auto-parts and components conglomerate, lea", bio: "Peasant-born former ironsmith who co-founded a small agricultural-machinery factory with six other farmers in 1969 and built it into Wanxiang Group, a major auto-parts and components conglomerate, leading the company until his death in October 2017." },
  { slug: "pan-shiyi", name: "Pan Shiyi", birthYear: 1963, sortOrder: 42, shortDescription: "Co-founded SOHO China with wife Zhang Xin in 1995, building it into one of China's leading real estate developers known for landmark Beijing office projects, then resigned as chairman in September 202", bio: "Co-founded SOHO China with wife Zhang Xin in 1995, building it into one of China's leading real estate developers known for landmark Beijing office projects, then resigned as chairman in September 2022 -- after a failed 2020-2021 attempt to sell the company to Blackstone -- to focus on philanthropy and the arts, having since relocated primarily to the United States." },
  { slug: "pony-ma", name: "Pony Ma", birthYear: 1971, sortOrder: 43, shortDescription: "Shenzhen University computer-science graduate who co-founded Tencent in 1998 with four classmates, launched the OICQ messaging service that became QQ, and continues to lead the company as chairman and", bio: "Shenzhen University computer-science graduate who co-founded Tencent in 1998 with four classmates, launched the OICQ messaging service that became QQ, and continues to lead the company as chairman and CEO of the Shenzhen-based technology, gaming, entertainment and financial-services conglomerate." },
  { slug: "qin-yinglin", name: "Qin Yinglin", birthYear: null, sortOrder: 44, shortDescription: "Founded Muyuan Foods and built it into the world's largest pig-farming and breeding operation, stepping down from all executive and board roles on June 3, 2026 to become Lifetime Honorary Chairman and", bio: "Founded Muyuan Foods and built it into the world's largest pig-farming and breeding operation, stepping down from all executive and board roles on June 3, 2026 to become Lifetime Honorary Chairman and head of the company's research institute, in a formally completed leadership transition." },
  { slug: "ren-jianxin", name: "Ren Jianxin", birthYear: 1958, sortOrder: 45, shortDescription: "Founded Bluestar, a small industrial-solvents factory, in 1984 with a RMB 10,000 loan and seven employees, then from 1996 built the state-owned ChemChina empire by taking control of more than 100 trou", bio: "Founded Bluestar, a small industrial-solvents factory, in 1984 with a RMB 10,000 loan and seven employees, then from 1996 built the state-owned ChemChina empire by taking control of more than 100 troubled, government-owned chemical factories across China, later leading ChemChina's $43 billion acquisition of Swiss agribusiness giant Syngenta and taking the chairmanship of Italian tire maker Pirelli." },
  { slug: "ren-zhengfei", name: "Ren Zhengfei", birthYear: 1944, sortOrder: 46, shortDescription: "Former People's Liberation Army engineer who founded Huawei in Shenzhen in 1987 with 21,000 yuan in capital and has served as its CEO continuously since 1988, building it into the world's largest tele", bio: "Former People's Liberation Army engineer who founded Huawei in Shenzhen in 1987 with 21,000 yuan in capital and has served as its CEO continuously since 1988, building it into the world's largest telecommunications equipment maker." },
  { slug: "richard-liu", name: "Richard Liu (Liu Qiangdong)", birthYear: null, sortOrder: 47, shortDescription: "Founded JD.com in 2004, built it into one of China's largest e-commerce platforms, and handed the CEO role to longtime executive Xu Lei in April 2022 while remaining chairman.", bio: "Founded JD.com in 2004, built it into one of China's largest e-commerce platforms, and handed the CEO role to longtime executive Xu Lei in April 2022 while remaining chairman." },
  { slug: "robin-li", name: "Robin Li", birthYear: null, sortOrder: 48, shortDescription: "Former Infoseek search engineer who co-founded Baidu in January 2000, has served as chairman since the company's inception and as CEO since February 2004, and built Baidu into China's dominant search ", bio: "Former Infoseek search engineer who co-founded Baidu in January 2000, has served as chairman since the company's inception and as CEO since February 2004, and built Baidu into China's dominant search engine." },
  { slug: "rong-desheng", name: "Rong Desheng", birthYear: 1875, sortOrder: 49, shortDescription: "Younger of the two Rong brothers, responsible for management and technical development of the family's flour and textile empire; assumed full leadership after 1938 and refused to sell the business to ", bio: "Younger of the two Rong brothers, responsible for management and technical development of the family's flour and textile empire; assumed full leadership after 1938 and refused to sell the business to Japanese interests during wartime pressure." },
  { slug: "rong-zongjing", name: "Rong Zongjing", birthYear: 1873, sortOrder: 50, shortDescription: "Wuxi-born industrialist who, with younger brother Rong Desheng, built China's largest privately owned flour-milling and cotton-textile empire in the Republican era, reportedly controlling roughly a th", bio: "Wuxi-born industrialist who, with younger brother Rong Desheng, built China's largest privately owned flour-milling and cotton-textile empire in the Republican era, reportedly controlling roughly a third of China's flour output and 30 percent of its cotton output by the early 1920s." },
  { slug: "shi-zhengrong", name: "Shi Zhengrong", birthYear: 1963, sortOrder: 51, shortDescription: "Chinese-Australian solar-technology PhD who returned to China in 2001 with backing from the Wuxi city government to found Suntech Power, briefly became China's richest person after its 2005 NYSE listi", bio: "Chinese-Australian solar-technology PhD who returned to China in 2001 with backing from the Wuxi city government to found Suntech Power, briefly became China's richest person after its 2005 NYSE listing at a peak $16 billion market capitalization, then was forced out as CEO in August 2012 and stripped of his chairmanship in March 2013 as the company collapsed into bankruptcy under $2.2 billion in debt." },
  { slug: "su-hua", name: "Su Hua", birthYear: null, sortOrder: 52, shortDescription: "Co-founded Kuaishou and led it as CEO before stepping down in October 2021 to focus on long-term strategy, transferring day-to-day operational responsibility to co-founder Cheng Yixiao while remaining", bio: "Co-founded Kuaishou and led it as CEO before stepping down in October 2021 to focus on long-term strategy, transferring day-to-day operational responsibility to co-founder Cheng Yixiao while remaining chairman with unchanged voting rights." },
  { slug: "wang-chuanfu", name: "Wang Chuanfu", birthYear: null, sortOrder: 53, shortDescription: "Founded battery maker BYD in 1995 and steered its diversification into electric vehicles, building it into a company that, per his own June 2026 statement, aims to become the world's largest automaker", bio: "Founded battery maker BYD in 1995 and steered its diversification into electric vehicles, building it into a company that, per his own June 2026 statement, aims to become the world's largest automaker by scale within five years." },
  { slug: "wang-jianlin", name: "Wang Jianlin", birthYear: 1954, sortOrder: 54, shortDescription: "Founder of the Dalian Wanda conglomerate (real estate, cinemas, cultural/tourism assets), who by September 2025 was subject to a Chinese court's high-consumption spending restrictions alongside Wanda ", bio: "Founder of the Dalian Wanda conglomerate (real estate, cinemas, cultural/tourism assets), who by September 2025 was subject to a Chinese court's high-consumption spending restrictions alongside Wanda and several subsidiaries over unpaid debts tied to a major Wuhan development project." },
  { slug: "wang-ning", name: "Wang Ning", birthYear: 1987, sortOrder: 55, shortDescription: "Founded Pop Mart in 2010 as a variety store in Beijing's Zhongguancun district inspired by Japanese gashapon vending machines, took it public on the Hong Kong Stock Exchange in December 2020, and cont", bio: "Founded Pop Mart in 2010 as a variety store in Beijing's Zhongguancun district inspired by Japanese gashapon vending machines, took it public on the Hong Kong Stock Exchange in December 2020, and continues to lead it as CEO through the global viral popularity of its Labubu toy line." },
  { slug: "wang-wei-sf-express", name: "Wang Wei (Dick Wang)", birthYear: 1970, sortOrder: 56, shortDescription: "Founded SF Express in the early 1990s to serve Hong Kong-bound manufacturers in Guangdong's Shunde district, built it into a major logistics conglomerate, and remains its chairman and majority shareho", bio: "Founded SF Express in the early 1990s to serve Hong Kong-bound manufacturers in Guangdong's Shunde district, built it into a major logistics conglomerate, and remains its chairman and majority shareholder." },
  { slug: "wang-xing", name: "Wang Xing", birthYear: 1979, sortOrder: 57, shortDescription: "Serial entrepreneur behind several failed startups (a Friendster clone, a Twitter clone called Fanfou) before co-founding Meituan in 2010, which he has led as CEO ever since, building it into China's ", bio: "Serial entrepreneur behind several failed startups (a Friendster clone, a Twitter clone called Fanfou) before co-founding Meituan in 2010, which he has led as CEO ever since, building it into China's dominant local-services and food-delivery platform." },
  { slug: "wei-jianjun", name: "Wei Jianjun", birthYear: 1964, sortOrder: 58, shortDescription: "Born in Baoding, Hebei, he was appointed director of Great Wall Motor -- then a small, partly local-government-owned manufacturer founded in 1984 -- in 1990, grew it into one of China's leading pickup", bio: "Born in Baoding, Hebei, he was appointed director of Great Wall Motor -- then a small, partly local-government-owned manufacturer founded in 1984 -- in 1990, grew it into one of China's leading pickup-truck and SUV manufacturers, led its 1998 privatization and 2003 Hong Kong Stock Exchange listing, and remains chairman as GWM sold over 1.3 million vehicles globally in 2025 across brands including Haval, Wey, Tank, Poer, and Ora." },
  { slug: "william-li", name: "William Li (Li Bin)", birthYear: null, sortOrder: 59, shortDescription: "Founded electric-vehicle maker NIO and continues to lead it as chairman and CEO; delivered a July 2026 speech at Peking University 30 years after his own time there, according to CnEVPost.", bio: "Founded electric-vehicle maker NIO and continues to lead it as chairman and CEO; delivered a July 2026 speech at Peking University 30 years after his own time there, according to CnEVPost." },
  { slug: "xu-jiayin", name: "Xu Jiayin", birthYear: 1958, sortOrder: 60, shortDescription: "Former steelworker who founded Evergrande and built it into China's largest real-estate developer before its 2021 default on roughly $300 billion in liabilities; detained by Chinese authorities in 202", bio: "Former steelworker who founded Evergrande and built it into China's largest real-estate developer before its 2021 default on roughly $300 billion in liabilities; detained by Chinese authorities in 2023, pleaded guilty in April 2026 to fraud, embezzlement and bribery charges, and was sentenced to life imprisonment by the Shenzhen Intermediate People's Court on August 20, 2026." },
  { slug: "yang-guoqiang", name: "Yang Guoqiang", birthYear: 1955, sortOrder: 61, shortDescription: "Founder of Country Garden Holdings, once China's largest home builder by sales, who tendered his resignation as chairman and executive director for age reasons effective March 1, 2023, handing the cha", bio: "Founder of Country Garden Holdings, once China's largest home builder by sales, who tendered his resignation as chairman and executive director for age reasons effective March 1, 2023, handing the chairmanship to his daughter Yang Huiyan while continuing to participate in corporate operations as a special advisor, amid China's broader property-sector debt crisis." },
  { slug: "yu-minhong", name: "Yu Minhong (Michael Yu)", birthYear: null, sortOrder: 62, shortDescription: "Founded New Oriental, China's largest private off-campus education company, and after Beijing's 2021 ban on for-profit tutoring devastated the business, personally pivoted into live-streaming e-commer", bio: "Founded New Oriental, China's largest private off-campus education company, and after Beijing's 2021 ban on for-profit tutoring devastated the business, personally pivoted into live-streaming e-commerce on Douyin, an initiative he called the 'third revolution of business.'" },
  { slug: "zhang-chaoyang", name: "Zhang Chaoyang (Charles Zhang)", birthYear: 1964, sortOrder: 63, shortDescription: "MIT-trained physicist who founded Sohu, one of China's earliest internet portals, listed it on NASDAQ in 2000, and has more recently taken on public roles as an educator and commentator, including urg", bio: "MIT-trained physicist who founded Sohu, one of China's earliest internet portals, listed it on NASDAQ in 2000, and has more recently taken on public roles as an educator and commentator, including urging students to reconsider graduate school and defer career plans." },
  { slug: "zhang-jian", name: "Zhang Jian", birthYear: 1853, sortOrder: 64, shortDescription: "Qing-dynasty top imperial exam scholar who turned to industry after 1895, founding the Dasheng Cotton Mill in Nantong and framing industrialization as a way to strengthen China against foreign economi", bio: "Qing-dynasty top imperial exam scholar who turned to industry after 1895, founding the Dasheng Cotton Mill in Nantong and framing industrialization as a way to strengthen China against foreign economic encroachment." },
  { slug: "zhang-ruimin", name: "Zhang Ruimin", birthYear: 1949, sortOrder: 65, shortDescription: "Took over a small, failing Qingdao refrigerator factory in 1984 and built it into global appliance group Haier, known for strict quality-control discipline and later for the 'Rendanheyi' decentralized", bio: "Took over a small, failing Qingdao refrigerator factory in 1984 and built it into global appliance group Haier, known for strict quality-control discipline and later for the 'Rendanheyi' decentralized management model, before stepping down as chairman in November 2021." },
  { slug: "zhang-xin", name: "Zhang Xin", birthYear: 1965, sortOrder: 66, shortDescription: "Left Beijing for Hong Kong at 14, worked in garment and electronics factories to save for overseas study, earned a scholarship-funded education in the UK, worked in finance in Hong Kong and New York, ", bio: "Left Beijing for Hong Kong at 14, worked in garment and electronics factories to save for overseas study, earned a scholarship-funded education in the UK, worked in finance in Hong Kong and New York, then co-founded SOHO China with husband Pan Shiyi in 1995, building it into a major Beijing office developer before stepping down as CEO in September 2022 and shifting business activities toward the United States via Closer Media and Closer Properties." },
  { slug: "zhang-yiming", name: "Zhang Yiming", birthYear: 1983, sortOrder: 67, shortDescription: "Nankai University-trained engineer who founded ByteDance in 2012, developed news aggregator Toutiao and short-video platform Douyin (known internationally as TikTok), and stepped down as CEO in Novemb", bio: "Nankai University-trained engineer who founded ByteDance in 2012, developed news aggregator Toutiao and short-video platform Douyin (known internationally as TikTok), and stepped down as CEO in November 2021 while retaining the chairman title and majority voting control." },
  { slug: "zhang-yin", name: "Zhang Yin (Cheung Yan)", birthYear: 1957, sortOrder: 68, shortDescription: "Former Guangdong textile-factory bookkeeper who moved to Shenzhen to work in paper trading, then founded Nine Dragons Paper, a recycling company that imports US scrap paper into China and turns it int", bio: "Former Guangdong textile-factory bookkeeper who moved to Shenzhen to work in paper trading, then founded Nine Dragons Paper, a recycling company that imports US scrap paper into China and turns it into cardboard for export packaging, becoming China's biggest paper maker." },
  { slug: "zhang-yong", name: "Zhang Yong", birthYear: null, sortOrder: 69, shortDescription: "Founded the Haidilao hot pot chain and, after some years focusing on high-level strategy as chairman, resumed direct CEO control in January 2026 to lead a 'second revolution' strategic overhaul as ear", bio: "Founded the Haidilao hot pot chain and, after some years focusing on high-level strategy as chairman, resumed direct CEO control in January 2026 to lead a 'second revolution' strategic overhaul as earnings cooled and China's dining sector slowed." },
  { slug: "zhong-shanshan", name: "Zhong Shanshan", birthYear: 1954, sortOrder: 70, shortDescription: "Former journalist and Cultural Revolution-era construction laborer who founded bottled-water company Nongfu Spring in 1996 and built it into China's largest bottled-water maker, and was re-appointed c", bio: "Former journalist and Cultural Revolution-era construction laborer who founded bottled-water company Nongfu Spring in 1996 and built it into China's largest bottled-water maker, and was re-appointed chairman of its ninth board of directors effective May 19, 2026." },
  { slug: "zhou-hongyi", name: "Zhou Hongyi", birthYear: 1970, sortOrder: 71, shortDescription: "Xi'an Jiaotong University-trained entrepreneur who founded search-keyword company 3721 in 1998, sold it to Yahoo! in 2004 for $120 million, then left after management disagreements to found internet-s", bio: "Xi'an Jiaotong University-trained entrepreneur who founded search-keyword company 3721 in 1998, sold it to Yahoo! in 2004 for $120 million, then left after management disagreements to found internet-security company Qihoo 360." },
  { slug: "zong-qinghou", name: "Zong Qinghou", birthYear: 1945, sortOrder: 72, shortDescription: "Former sent-down youth and salt-farm laborer who built Wahaha into China's leading beverage company, won a prolonged legal and trademark battle against joint-venture partner Danone in the mid-2000s, a", bio: "Former sent-down youth and salt-farm laborer who built Wahaha into China's leading beverage company, won a prolonged legal and trademark battle against joint-venture partner Danone in the mid-2000s, and served as an NPC delegate from 2002-2018 before dying in February 2024." },
];

import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();

async function main() {
  // Keep person rows in sync with the PEOPLE roster (status, descriptions).
  for (const p of PEOPLE) {
    await db.person.upsert({
      where: { slug: p.slug },
      update: { status: "active" },
      create: {
        slug: p.slug,
        name: p.name,
        birthYear: p.birthYear,
        sortOrder: p.sortOrder,
        shortDescription: p.shortDescription,
        bio: p.bio,
        status: p.status || "active",
      },
    });
  }

  const industryMap: Record<string, string> = {};
  await db.$transaction(async (tx) => {
    for (const ind of INDUSTRIES) {
      const rec = await tx.industry.upsert({ where: { slug: ind.slug }, update: {}, create: ind });
      industryMap[ind.slug] = rec.id;
    }
    for (const company of COMPANIES) {
      const { industry, ...rest } = company;
      const existing = await tx.company.findUnique({ where: { slug: company.slug } });
      if (!existing)
        await tx.company.create({ data: { ...rest, industryId: industryMap[industry] } });
    }
    for (const t of THEMES) {
      const e = await tx.theme.findUnique({ where: { slug: t.slug } });
      if (!e) await tx.theme.create({ data: t });
    }
    for (const c of CONCEPTS) {
      const e = await tx.concept.findUnique({ where: { slug: c.slug } });
      if (!e) await tx.concept.create({ data: c });
    }
    for (const ev of EVENTS) {
      const e = await tx.event.findUnique({ where: { slug: ev.slug } });
      if (!e) await tx.event.create({ data: ev });
    }
    console.log("entities ensured");
  }, { maxWait: 30000, timeout: 300000 });

  const themeIds = Object.fromEntries((await db.theme.findMany()).map((t) => [t.slug, t.id]));
  const conceptIds = Object.fromEntries((await db.concept.findMany()).map((c) => [c.slug, c.id]));
  const companyIds = Object.fromEntries((await db.company.findMany()).map((c) => [c.slug, c.id]));
  const eventIds = Object.fromEntries((await db.event.findMany()).map((e) => [e.slug, e.id]));
  const personIds = Object.fromEntries(
    (await db.person.findMany()).map((p) => [p.slug, p.id])
  );

  let totalPassages = 0;

  // Optional CLI filter: `bun scripts/ingest/import-db.ts fisher icahn` imports only
// those corpora files. Without args, imports everything (full re-seed).
// `--delta` (anywhere in args): skip sources whose DB passage count already
// matches the corpus file — imports ONLY what changed. Safe for passage IDs
// of unchanged sources (no delete/recreate churn, bookmarks keep working).
// Reads data/corpora/ recursively so subdirectories like `earnings-calls/` are picked up.
const rawArgs = process.argv.slice(2);
const deltaMode = rawArgs.includes("--delta");
const onlyFiles = rawArgs
  .filter((a) => !a.startsWith("--"))
  .map((a) => (a.endsWith(".jsonl") ? a : `${a}.jsonl`));
const corpusFiles = (readdirSync("data/corpora", { recursive: true }) as unknown[]).filter(
  (f): f is string => typeof f === "string",
)
  .filter((f) => f.endsWith(".jsonl"))
  // Normalize Windows-style separators and drop leading "./" if present so the
  // CLI filter can match bare filenames like `coca-cola.jsonl` regardless of subdirectory.
  .map((f) => f.replace(/^\.\//, ""))
  .filter((f) => onlyFiles.length === 0 || onlyFiles.some((o) => f === o || f.endsWith(`/${o}`) || f.endsWith(`\\${o}`)));
  for (const file of corpusFiles) {
    const lines = (await Bun.file(`data/corpora/${file}`).text())
      .split("\n")
      .filter(Boolean)
      .map((l) => JSON.parse(l) as CorpusLine);

    for (const line of lines) {
      const personId = personIds[line.personSlug];
      if (!personId) continue;

      const valid = line.passages.filter((p) => p.text && p.text.length >= 50);

      let source = await db.source.findUnique({ where: { slug: line.source.slug } });

      // DELTA MODE: source exists with the same passage count → nothing to do.
      // Keeps unchanged passages (and their IDs / junctions / bookmarks) intact.
      if (deltaMode && source) {
        const dbCount = await db.passage.count({ where: { sourceId: source.id } });
        if (dbCount === valid.length) continue;
      }

      if (!source) {
        source = await db.source.create({
          data: {
            personId,
            slug: line.source.slug,
            title: line.source.title,
            year: line.source.year,
            sourceType: line.source.sourceType,
            publisher: line.source.publisher,
            url: line.source.url,
            provenanceStatus: "verified",
          },
        });
      } else {
        await db.source.update({
          where: { id: source.id },
          data: { year: line.source.year, title: line.source.title },
        });
      }

      await db.passage.deleteMany({ where: { sourceId: source.id } });

      if (!valid.length) continue;

      // BULK: one insert per source instead of thousands of round trips
      await db.passage.createMany({
        data: valid.map((p) => ({
          sourceId: source!.id,
          text: p.text,
          sequence: p.sequence,
          // PAYWALL DORMANT — everything imports public. Corpus files may
          // still carry legacy "pro" flags; they are ignored while the whole
          // site is free. Flip here if the paywall is ever re-activated.
          visibility: "public",
        })),
      });

      const created = await db.passage.findMany({
        where: { sourceId: source.id },
        select: { id: true, sequence: true },
      });
      const bySeq = new Map(created.map((r) => [r.sequence, r.id]));

      const themeRows: { passageId: string; themeId: string }[] = [];
      const conceptRows: { passageId: string; conceptId: string }[] = [];
      const companyRows: { passageId: string; companyId: string }[] = [];
      const eventRows: { passageId: string; eventId: string }[] = [];
      for (const p of valid) {
        const pid = bySeq.get(p.sequence);
        if (!pid) continue;
        for (const s of p.themes ?? []) { const id = themeIds[s]; if (id) themeRows.push({ passageId: pid, themeId: id }); }
        for (const s of p.concepts ?? []) { const id = conceptIds[s]; if (id) conceptRows.push({ passageId: pid, conceptId: id }); }
        for (const s of p.companies ?? []) { const id = companyIds[s]; if (id) companyRows.push({ passageId: pid, companyId: id }); }
        for (const s of p.events ?? []) { const id = eventIds[s]; if (id) eventRows.push({ passageId: pid, eventId: id }); }
      }
      if (themeRows.length) await db.passageTheme.createMany({ data: themeRows, skipDuplicates: true });
      if (conceptRows.length) await db.passageConcept.createMany({ data: conceptRows, skipDuplicates: true });
      if (companyRows.length) await db.passageCompany.createMany({ data: companyRows, skipDuplicates: true });
      if (eventRows.length) await db.passageEvent.createMany({ data: eventRows, skipDuplicates: true });

      totalPassages += valid.length;
    }
    process.stdout.write(`${file} done (${totalPassages} total)\n`);
  }

  const counts = {
    people: await db.person.count(),
    sources: await db.source.count(),
    passages: await db.passage.count(),
  };
  console.log("IMPORT COMPLETE", JSON.stringify(counts));
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
